import { createHash } from "node:crypto";
import * as XLSX from "xlsx";
import type { InspectedDocument } from "../../lib/files";
import type { ObservedCell, ObservedDocument, ObservedRegion } from "./contracts";
const hash=(value:unknown)=>createHash("sha256").update(typeof value==="string"?value:JSON.stringify(value)).digest("hex");
export async function observeDocument(document:InspectedDocument):Promise<ObservedDocument>{
 const format=document.extension.slice(1) as ObservedDocument["format"], contentHash=hash(document.buffer);
 if(format==="pdf"){const {default:parse}=await import("pdf-parse/lib/pdf-parse.js"),parsed=await parse(document.buffer),text=parsed.text.trim();const cells:ObservedCell[]=text.split(/\r?\n/).map((line,row)=>({row:row+1,column:1,raw:line,text:line,indentation:line.length-line.trimStart().length,evidenceHash:hash([contentHash,row,line])}));return{contractVersion:"observed-document.v1",filename:document.fileName,format,contentHash,regions:[{id:`page-text-${contentHash.slice(0,12)}`,name:"PDF text",kind:"page",index:1,cells,headings:cells.slice(0,5).map(x=>x.text).filter(Boolean),bounds:{startRow:1,endRow:cells.length,startColumn:1,endColumn:1}}],extraction:{adapter:"pdf-text.v1",textReliable:Boolean(text),warnings:text?[]:["image_only_or_unreadable"]}}}
 const workbook=XLSX.read(document.buffer,{type:"buffer",cellFormula:true,cellText:true,cellDates:true,cellStyles:true});const regions:ObservedRegion[]=workbook.SheetNames.map((name,index)=>{const sheet=workbook.Sheets[name],range=XLSX.utils.decode_range(sheet["!ref"]??"A1"),merges=sheet["!merges"]??[],cells:ObservedCell[]=[];for(let row=range.s.r;row<=range.e.r;row++)for(let column=range.s.c;column<=range.e.c;column++){const address=XLSX.utils.encode_cell({r:row,c:column}),cell=sheet[address];if(!cell)continue;const merged=merges.find(m=>row>=m.s.r&&row<=m.e.r&&column>=m.s.c&&column<=m.e.c);cells.push({row:row+1,column:column+1,raw:cell.v,text:cell.w??String(cell.v??""),formula:cell.f,numberFormat:cell.z,styleId:cell.s?.toString?Number(cell.s):undefined,indentation:Number(cell.s?.alignment?.indent??0),mergedRange:merged?XLSX.utils.encode_range(merged):undefined,evidenceHash:hash([contentHash,name,address,cell.v,cell.f])})}return{id:`region-${hash([contentHash,name,index]).slice(0,16)}`,name,kind:"sheet",index:index+1,cells,headings:cells.filter(c=>c.row<=5&&c.text).map(c=>c.text),bounds:{startRow:range.s.r+1,endRow:range.e.r+1,startColumn:range.s.c+1,endColumn:range.e.c+1}}});return{contractVersion:"observed-document.v1",filename:document.fileName,format,contentHash,regions,extraction:{adapter:`${format}-workbook.v1`,textReliable:true,warnings:[]}};
}
