import {createConfiguredResponse,type OpenAITransport} from "../../lib/openai";
import {CANONICAL_CONCEPTS,type CanonicalConcept,type Period,type RowRole,type SourceRow} from "../schema";

export const SEMANTIC_RESOLVER_CONTRACT_VERSION="semantic-resolver.v2" as const;
export type SemanticRequest={statementType:"income_statement";sourceLabel:string;normalizedLabel:string;rowRole:RowRole;neighbourLabels:string[];hierarchy:string[];candidateConcepts:CanonicalConcept[];signPattern:"positive"|"negative"|"mixed";relationshipConstraints:string[];currency:string|null;scale:number|null};
export type SemanticResponse={concept:CanonicalConcept|null;confidence:number;provider:string|null;model:string|null;contractVersion:typeof SEMANTIC_RESOLVER_CONTRACT_VERSION;fallbackReason:string|null};
export type SemanticProvider=(request:Readonly<SemanticRequest>)=>Promise<unknown>;
export async function resolveBoundedSemantic(request:SemanticRequest,provider?:SemanticProvider):Promise<SemanticResponse>{const unresolved=(reason:string):SemanticResponse=>({concept:null,confidence:0,provider:null,model:null,contractVersion:SEMANTIC_RESOLVER_CONTRACT_VERSION,fallbackReason:reason});if(!provider)return unresolved("provider_unavailable");try{const raw=await provider(Object.freeze({...request,candidateConcepts:[...request.candidateConcepts]}));if(!raw||typeof raw!=="object")return unresolved("invalid_output");const x=raw as Record<string,unknown>;if(typeof x.concept!=="string"||!request.candidateConcepts.includes(x.concept as CanonicalConcept)||!(CANONICAL_CONCEPTS as readonly string[]).includes(x.concept)||typeof x.confidence!=="number"||x.confidence<0||x.confidence>1)return unresolved("invalid_output");return{concept:x.concept as CanonicalConcept,confidence:x.confidence,provider:typeof x.provider==="string"?x.provider:"configured",model:typeof x.model==="string"?x.model:null,contractVersion:SEMANTIC_RESOLVER_CONTRACT_VERSION,fallbackReason:null}}catch{return unresolved("provider_error")}}

export type StatementSection="header"|"metadata"|"p_and_l"|"oci"|"attribution"|"unresolved";
export type StatementResolution={title:string|null;currency:string|null;scale:number|null;rows:Array<{rowNumber:number;section:StatementSection;role:RowRole;concept:CanonicalConcept|null;confidence:number;supportingEvidence:string[];contradictions:string[]}>;provider:"openai";model:string;resolverVersion:string};
export type WholeStatementInput={title:string|null;rows:SourceRow[];periods:Period[];currency:string|null;scale:number|null;candidates:Record<number,CanonicalConcept[]>;signPatterns:Record<number,"positive"|"negative"|"mixed">;relationships:string[]};

const positive=(value:string|undefined,fallback:number,max:number)=>{const n=Number(value);return Number.isInteger(n)&&n>0?Math.min(n,max):fallback};
export function getFinancialResolverConfig(){const apiKey=process.env.OPENAI_API_KEY?.trim(),model=process.env.FINANCIAL_SEMANTIC_MODEL?.trim();return{enabled:process.env.FINANCIAL_SEMANTIC_RESOLVER_ENABLED==="true",apiKey,model,resolverVersion:process.env.FINANCIAL_SEMANTIC_RESOLVER_VERSION?.trim()||"2026-09-04",timeoutMs:positive(process.env.FINANCIAL_SEMANTIC_TIMEOUT_MS,30_000,60_000),attempts:positive(process.env.FINANCIAL_SEMANTIC_MAX_ATTEMPTS,2,3),maxRows:positive(process.env.FINANCIAL_SEMANTIC_MAX_ROWS,120,200),maxContextChars:positive(process.env.FINANCIAL_SEMANTIC_MAX_CONTEXT_CHARS,32_000,60_000)}};
const schema={type:"object",additionalProperties:false,required:["title","currency","scale","rows"],properties:{title:{type:["string","null"]},currency:{type:["string","null"],pattern:"^[A-Z]{3}$"},scale:{type:["number","null"],enum:[null,1,1000,1000000]},rows:{type:"array",items:{type:"object",additionalProperties:false,required:["rowNumber","section","role","concept","confidence","supportingEvidence","contradictions"],properties:{rowNumber:{type:"integer"},section:{type:"string",enum:["header","metadata","p_and_l","oci","attribution","unresolved"]},role:{type:"string",enum:["title","subtitle","metadata","period_header","financial_line","subtotal","total","spacer","note","unknown"]},concept:{type:["string","null"],enum:[...CANONICAL_CONCEPTS,null]},confidence:{type:"number",minimum:0,maximum:1},supportingEvidence:{type:"array",maxItems:5,items:{type:"string",maxLength:160}},contradictions:{type:"array",maxItems:5,items:{type:"string",maxLength:160}}}}}}} as const;
export async function resolveWholeStatement(input:WholeStatementInput,injected?:OpenAITransport):Promise<{resolution:StatementResolution|null;reason:string|null}>{const config=getFinancialResolverConfig();if(!config.enabled)return{resolution:null,reason:"feature_disabled"};if(!config.apiKey||!config.model)return{resolution:null,reason:"provider_unavailable"};const rows=input.rows.slice(0,config.maxRows).map((row,index)=>({rowNumber:row.rowNumber,label:row.label.slice(0,240),role:row.role,indentation:row.indentation??0,parentRowNumber:row.parentRowNumber??null,neighbours:[input.rows[index-1]?.label,input.rows[index+1]?.label].filter(Boolean),candidateConcepts:input.candidates[row.rowNumber]??[],signPattern:input.signPatterns[row.rowNumber]??"mixed"}));const payload=JSON.stringify({statementTitle:input.title,rows,periods:input.periods.map(p=>({header:p.originalHeader,type:p.type,designation:p.designation})),currencyEvidence:input.currency,scaleEvidence:input.scale,deterministicRelationships:input.relationships}).slice(0,config.maxContextChars);try{const response=await createConfiguredResponse({model:config.model,store:false,instructions:"Interpret the complete English financial statement. Separate profit or loss, OCI, total comprehensive income, attribution, metadata and headers. Select concepts only from each row's candidateConcepts. Return null rather than guess. Currency and scale require explicit document evidence. Never alter values, periods, evidence, validation or readiness.",input:payload,max_output_tokens:5000,text:{format:{type:"json_schema",name:"income_statement_interpretation",strict:true,schema}}},{apiKey:config.apiKey,timeoutMs:config.timeoutMs,attempts:config.attempts},injected);if(response.status!=="completed")return{resolution:null,reason:"incomplete"};const raw=JSON.parse(response.output_text) as Omit<StatementResolution,"provider"|"model"|"resolverVersion">;const permitted=new Map(rows.map(r=>[r.rowNumber,new Set(r.candidateConcepts)]));if(!Array.isArray(raw.rows)||raw.rows.some(r=>!permitted.has(r.rowNumber)||(r.concept!==null&&!permitted.get(r.rowNumber)!.has(r.concept))||r.confidence<0||r.confidence>1))return{resolution:null,reason:"invalid_output"};return{resolution:{...raw,provider:"openai",model:config.model,resolverVersion:config.resolverVersion},reason:null}}catch{return{resolution:null,reason:"provider_error"}}}
