import type { DecisionWorkspaceProjection, UserSynthesisView } from "./types";
import styles from "./concierge-lab.module.css";

export default function ProblemStatePanel({ projection, synthesis }: { projection: DecisionWorkspaceProjection; synthesis: UserSynthesisView | null }) {
  return <div className={styles.problemState}>
    <div className={styles.workspaceTitle}><div><span>Shared Problem State</span><h1>{projection.operational_problem}</h1></div><Readiness value={projection.decision_readiness} /></div>
    <section className={styles.problemCompare}><div><span>Declared Problem</span><p>{projection.declared_problem}</p></div><div><span>Operational Problem</span><p>{projection.operational_problem}</p></div></section>
    <EpistemicControl projection={projection} />
    <div className={styles.stateGrid}>
      <Section title="Validated Evidence" count={projection.validated_evidence.length}>{projection.validated_evidence.map((item) => <article key={item.id}><Tag>{item.evidence_type.replaceAll("_", " ")}</Tag><p>{item.proposition}</p><small>{item.source}</small></article>)}</Section>
      <Section title="Unverified Claims" count={projection.reported_claims.length}>{projection.reported_claims.map((item) => <article key={item.id}><Tag>{item.status}</Tag><p>{item.proposition}</p><small>Source · {item.source}</small></article>)}</Section>
      <Section title="Active Hypotheses" count={projection.active_hypotheses.length}>{projection.active_hypotheses.map((item) => <article key={item.id}><Tag>{item.status}</Tag><p>{item.proposition}</p><small>Support {item.support} · Against {item.against}</small></article>)}</Section>
      <Section title="Unknowns" count={projection.unknowns.length}>{projection.unknowns.map((item) => <details key={item.id}><summary><i>?</i><span>{item.variable}</span><Tag>{item.materiality}</Tag></summary><div><small>Why needed</small><p>{item.why_needed}</p><small>Clarification target</small><p>{item.clarification_target}</p></div></details>)}</Section>
      <Section title="Contradictions" count={projection.contradictions.length}>{projection.contradictions.map((item) => <article key={item.id}><Tag>{item.status}</Tag><p><strong>Reported</strong> {item.proposition_a}</p><p><strong>Evidence</strong> {item.proposition_b}</p><small>{item.issue}</small></article>)}</Section>
    </div>
    <Analysis projection={projection} />
    {synthesis && <Synthesis view={synthesis} human={projection.human_decision_required} />}
  </div>;
}

function Readiness({ value }: { value: string }) { return <div className={styles.readiness}><span>Decision readiness</span><strong>{value.replaceAll("_", " ")}</strong>{value === "ANALYSIS_READY" && <small>Analysis may proceed; no final decision yet.</small>}</div>; }
function EpistemicControl({ projection }: { projection: DecisionWorkspaceProjection }) { const veto = projection.epistemic_veto; return <section className={`${styles.epistemic} ${veto.active ? styles.epistemicActive : ""}`}><div><span>Module B · Epistemic Control</span><strong>{veto.verdict.replaceAll("_", " ")}</strong></div><p>{veto.active ? veto.blocking_reason : "No active veto. Findings remain subject to their stated limitations."}</p><dl><div><dt>Required next action</dt><dd>{veto.required_next_action.replaceAll("_", " ")}</dd></div>{veto.unknown_ids.length > 0 && <div><dt>Affected unknowns</dt><dd>{veto.unknown_ids.join(", ")}</dd></div>}</dl></section>; }
function Section({ title, count, children }: { title: string; count: number; children: React.ReactNode }) { return <section className={styles.stateSection}><header><h2>{title}</h2><span>{count}</span></header><div>{count ? children : <p className={styles.empty}>No objects in this state.</p>}</div></section>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className={styles.tag}>{children}</span>; }

function Analysis({ projection }: { projection: DecisionWorkspaceProjection }) { if (!projection.routing_plan.ready && !projection.active_agents.length) return null; return <section className={styles.analysis}><div className={styles.sectionHeading}><span>Analysis layer</span><h2>Analytical modules</h2></div><div className={styles.agentGrid}>{projection.active_agents.map((agent) => <article key={agent.id}><div><Tag>{agent.status}</Tag><small>{agent.domain}</small></div><h3>{agent.label}</h3><p>{agent.task}</p></article>)}</div>{projection.validated_agent_findings.length > 0 && <div className={styles.findings}><h3>Validated agent findings</h3>{projection.validated_agent_findings.map((finding) => <article key={finding.id}><div><strong>{projection.active_agents.find((item) => item.id === finding.agent_id)?.label ?? finding.agent_id}</strong><Tag>{finding.type}</Tag></div><p>{finding.proposition}</p>{finding.limitations.map((item) => <small key={item}>Limitation · {item}</small>)}</article>)}</div>}{projection.reconciliation.length > 0 && <div className={styles.reconciliation}><h3>Cross-agent reconciliation</h3>{projection.reconciliation.map((item) => <article key={item.id}><div><p>{item.left}</p><span>↔</span><p>{item.right}</p></div><Tag>{item.classification}</Tag></article>)}</div>}</section>; }

function Synthesis({ view, human }: { view: UserSynthesisView; human: boolean }) { const rows: [string, string[]][] = [["What we know", view.what_we_know], ["What we infer", view.what_we_infer], ["What remains unknown", view.what_remains_unknown], ["What matters for the decision", view.what_matters_for_decision], ["Recommended actions", view.recommended_actions], ["What would change the recommendation", view.what_would_change_recommendation]]; return <section className={styles.synthesis}><div className={styles.sectionHeading}><span>Final admissibility · {view.epistemic_status.replaceAll("_", " ")}</span><h2>Decision Synthesis</h2>{human && <strong>Human decision required</strong>}</div><div>{rows.map(([title, values]) => <article key={title}><h3>{title}</h3>{values.map((value) => <p key={value}>{value}</p>)}</article>)}</div></section>; }
