import type { ContradictionView, DecisionWorkspaceProjection, EvidenceView, UnknownView, UserSynthesisView } from "./types";
import styles from "./concierge-lab.module.css";

export default function ProblemStatePanel({ projection, synthesis, onUnknown, selectedId, onSelect }: { projection: DecisionWorkspaceProjection; synthesis: UserSynthesisView | null; onUnknown: (id: string, question: string) => void; selectedId: string | null; onSelect: (id: string | null) => void }) {
  return <div className={styles.problemState}><div className={styles.workspaceTitle}><div><span>Shared Problem State</span><h1>{projection.operational_problem ?? "Operational problem"}</h1></div></div><section className={styles.operationalProblem}><span>Operational problem</span><p>{projection.operational_problem ?? "Being formed"}</p>{!projection.operational_problem && <small>The initial statement is preserved, but the analytical problem has not yet been established.</small>}</section><Readiness projection={projection} /><EpistemicControl projection={projection} /><div className={styles.stateGrid}>
    <Section title="Validated Evidence" count={projection.validated_evidence.length} empty="No validated evidence yet">{projection.validated_evidence.map((item) => <EvidenceRecord key={item.id} item={item} selected={selectedId === item.id} onSelect={onSelect} />)}</Section>
    <Section title="Evidence Awaiting Validation" count={projection.unverified_evidence?.length ?? 0} empty="No evidence awaiting validation">{projection.unverified_evidence?.map((item) => <EvidenceRecord key={item.id} item={item} selected={selectedId === item.id} onSelect={onSelect} />)}</Section>
    <Section title="Unverified Claims" count={projection.reported_claims.length} empty="No unverified claims">{projection.reported_claims.map((item) => <article className={styles.unverified} key={item.id}><Tag>{item.status}</Tag><p>{item.proposition}</p><small>Source · {item.source}</small></article>)}</Section>
    <Section title="Critical Unknowns" count={projection.unknowns.length} empty="No unresolved unknowns">{projection.unknowns.map((item) => <UnknownRecord key={item.id} item={item} selected={selectedId === item.id} onUnknown={onUnknown} />)}</Section>
    <Section title="Contradictions" count={projection.contradictions.length} empty="No active contradictions">{projection.contradictions.map((item) => <ContradictionRecord key={item.id} item={item} selected={selectedId === item.id} onSelect={onSelect} />)}</Section>
    <Section title="Active Hypotheses" count={projection.active_hypotheses.length} empty="No active hypotheses">{projection.active_hypotheses.map((item) => <article className={styles.hypothesis} key={item.id}><Tag>{item.status}</Tag><p>{item.proposition}</p><small>Canonical support {item.support} · counter-evidence {item.against}</small></article>)}</Section>
  </div><Analysis projection={projection} />{synthesis && <Synthesis view={synthesis} human={projection.human_decision_required} />}</div>;
}
function Readiness({ projection }: { projection: DecisionWorkspaceProjection }) { const value = projection.decision_readiness; const ready = value === "ANALYSIS_READY"; return <section className={`${styles.readiness} ${ready ? styles.ready : ""}`}><span>Decision readiness</span><strong>{ready ? "Analysis ready" : "Clarification required"}</strong><p>{ready ? "The operational problem is defined and critical evidence requirements are resolved." : "Progress is paused while the most decision-critical uncertainty is clarified."}</p><small>{ready ? "Analysis is available in this Case" : `${projection.unknowns.length} unresolved unknowns · ${projection.contradictions.length} contradictions`}</small></section>; }
function EpistemicControl({ projection }: { projection: DecisionWorkspaceProjection }) { const veto = projection.epistemic_veto; return <section className={`${styles.epistemic} ${veto.active ? styles.epistemicActive : ""}`}><div><span>Next</span><strong>{veto.active ? "Resolve the current clarification" : "Continue to analysis"}</strong></div><p>{veto.active ? veto.blocking_reason ?? "More context is needed before responsible analysis can continue." : "No critical analytical blocker is active."}</p></section>; }
function Section({ title, count, empty, children }: { title: string; count: number; empty: string; children: React.ReactNode }) { return <section className={styles.stateSection}><header><h2>{title}</h2><span>{count}</span></header><div>{count ? children : <p className={styles.empty}>{empty}</p>}</div></section>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className={styles.tag}>{children}</span>; }
function sourceLabel(item: EvidenceView) { if (typeof item.source === "string") return item.source; const location = item.source.location ?? {}; return [item.source_filename ?? item.source.artifact_id, location.page && `Page ${location.page}`, location.sheet && `Sheet: ${location.sheet}`, location.cell && `Cell: ${location.cell}`, location.row && `Row ${location.row}`, location.column && `Column: ${location.column}`].filter(Boolean).join(" · "); }
function EvidenceRecord({ item, selected, onSelect }: { item: EvidenceView; selected: boolean; onSelect: (id: string | null) => void }) { const status = item.admission_status ?? item.evidence_type ?? "VALIDATED"; return <details open={selected} onToggle={(event) => { if (event.currentTarget.open) onSelect(item.id); }}><summary><i>{status === "VALIDATED" ? "✓" : "·"}</i><span>{item.proposition}</span><Tag>{status.replaceAll("_", " ")}</Tag></summary><div><small>Provenance</small><p>{sourceLabel(item)}</p>{item.formula && <><small>Formula</small><code>{item.formula}</code></>}</div></details>; }
function UnknownRecord({ item, selected, onUnknown }: { item: UnknownView; selected: boolean; onUnknown: (id: string, question: string) => void }) { return <article className={`${styles.unknown} ${selected ? styles.selectedObject : ""}`}><button type="button" onClick={() => onUnknown(item.id, item.clarification_target)} aria-label={`Focus clarification for ${item.variable}`}><i>?</i><span>{item.variable}</span><Tag>{item.materiality}</Tag></button><p>{item.why_needed}</p><small>Canonical ID · {item.id}</small><strong>Q* · {item.clarification_target}</strong></article>; }
function ContradictionRecord({ item, selected, onSelect }: { item: ContradictionView; selected: boolean; onSelect: (id: string | null) => void }) { return <details open={selected} onToggle={(event) => { if (event.currentTarget.open) onSelect(item.id); }}><summary><i>≠</i><span>{item.issue}</span><Tag>{item.status}</Tag></summary><div className={styles.mismatch}><section><small>Source A</small><p>{item.proposition_a}</p></section><section><small>Source B</small><p>{item.proposition_b}</p></section><p>Clarification is required; neither value is privileged.</p></div></details>; }
function Analysis({ projection }: { projection: DecisionWorkspaceProjection }) { const unlocked = projection.decision_readiness === "ANALYSIS_READY" || projection.active_agents.length > 0 || projection.analysis_run; if (!unlocked) return <section className={styles.analysisLocked}><span>Analysis</span><p>Available when canonical Decision Readiness reaches ANALYSIS_READY.</p></section>; const run = projection.analysis_run; return <section className={styles.analysis}><div className={styles.sectionHeading}><span>Same Case · continuous state</span><h2>Analysis</h2></div><dl className={styles.analysisBasis}><div><dt>Status</dt><dd>{run?.status ?? (projection.active_agents.length ? "EXECUTING" : "READY")}</dd></div><div><dt>State basis</dt><dd>{run?.input_state_version !== undefined ? `Version ${run.input_state_version}` : "Current canonical version"}</dd></div><div><dt>Final admissibility</dt><dd>{run?.final_admissibility_state ?? projection.epistemic_verdict}</dd></div></dl><div className={styles.agentGrid}>{projection.active_agents.map((capability) => <article key={capability.id}><Tag>{capability.status}</Tag><h3>{capability.task || capability.label}</h3><p>{capability.domain}</p><details><summary>Technical provenance</summary><small>{capability.id}</small></details></article>)}</div>{projection.validated_agent_findings.length > 0 && <div className={styles.findings}><h3>Audited findings</h3>{projection.validated_agent_findings.map((finding) => <article key={finding.id}><Tag>{finding.type}</Tag><p>{finding.proposition}</p>{finding.limitations.map((item) => <small key={item}>Limitation · {item}</small>)}</article>)}</div>}</section>; }
function Synthesis({ view, human }: { view: UserSynthesisView; human: boolean }) { const rows: [string, string[]][] = [["What we know", view.what_we_know], ["What we infer", view.what_we_infer], ["What remains unknown", view.what_remains_unknown], ["What matters", view.what_matters_for_decision], ["Recommended actions", view.recommended_actions], ["What would change this", view.what_would_change_recommendation]]; return <section className={styles.synthesis}><div className={styles.sectionHeading}><span>Final admissibility · {view.epistemic_status.replaceAll("_", " ")}</span><h2>Decision synthesis</h2>{human && <strong>Human decision required</strong>}</div><div>{rows.map(([title, values]) => <article key={title}><h3>{title}</h3>{values.map((value) => <p key={value}>{value}</p>)}</article>)}</div></section>; }
