import { createHash,randomUUID } from "node:crypto";
import type { FinancialRun,ReviewDecision } from "../schema";
import { replayFinancialReview,withFinancialRunIntegrity } from "../run";
import type { FinancialRunRepository } from "./contracts";
import { PersistenceConflictError } from "./contracts";
const snapshot=(run:FinancialRun,actor:string)=>{const payload={schemaVersion:run.schemaVersion,runId:run.runId,revision:run.revision??1,selectedStatement:run.source.selectedSection,periods:run.periods,values:run.values,currency:run.currency,unitScale:run.unitScale,evidence:run.evidence,reviewTasks:run.reviewTasks.filter(t=>t.state==="resolved"),controls:run.controls,validationSummary:run.validationSummary,validatedAt:new Date().toISOString(),validatedBy:actor};return{...payload,integrityHash:createHash("sha256").update(JSON.stringify(payload)).digest("hex")}};
export class FinancialRunService{constructor(private repository:FinancialRunRepository){}
 async create(actor:string,run:FinancialRun,file:{size:number;fingerprint:string}){const now=new Date().toISOString();const durable={...run,sessionScoped:false,source:{...run.source,fileSize:file.size,documentFingerprint:file.fingerprint},revision:1,createdAt:now,updatedAt:now,lastCompletedStage:run.workflow.filter(x=>x.state==="completed").at(-1)?.id};withFinancialRunIntegrity(durable);return this.repository.create(actor,durable,{type:"run_created",after:{status:durable.status,filename:durable.source.filename}})}
 list(actor:string){return this.repository.list(actor)} get(actor:string,id:string){return this.repository.get(actor,id)}
 async review(actor:string,id:string,expectedRevision:number,decision:ReviewDecision){const current=await this.owned(actor,id);this.writable(current,expectedRevision);const updated=replayFinancialReview(current,decision);updated.revision=expectedRevision+1;const event=decision.action==="remap"?"row_remapped":decision.action==="reject"?"review_decision_rejected":"review_decision_accepted";return this.repository.update(actor,updated,expectedRevision,{type:event,before:{taskId:decision.taskId},after:{action:decision.action,concept:decision.concept}},updated.status==="validated"?snapshot(updated,actor):undefined)}
 async archive(actor:string,id:string,expectedRevision:number){const current=await this.owned(actor,id);this.writable(current,expectedRevision);const updated={...current,status:"archived" as const,revision:expectedRevision+1};return this.repository.update(actor,updated,expectedRevision,{type:"run_archived",before:{status:current.status},after:{status:"archived"}})}
 async revise(actor:string,id:string,expectedRevision:number){const current=await this.owned(actor,id);if(current.status!=="validated"||current.revision!==expectedRevision)throw new Error("Only the current validated revision can be revised");const copy={...current,runId:randomUUID(),status:"review_required" as const,revision:1,parentRunId:current.runId,parentRevision:current.revision,validatedAt:null,createdAt:undefined,updatedAt:undefined,auditEvents:undefined};return this.repository.create(actor,copy,{type:"revision_created",before:{parentRunId:id,parentRevision:expectedRevision},after:{runId:copy.runId}})}
 private async owned(actor:string,id:string){const run=await this.repository.get(actor,id);if(!run)throw new Error("RUN_NOT_FOUND");return run}private writable(run:FinancialRun,revision:number){if(run.status==="archived"||run.status==="validated")throw new Error("RUN_READ_ONLY");if(run.revision!==revision)throw new PersistenceConflictError("Stale run revision")}}
