import { createHash,randomUUID } from "node:crypto";
import type { FinancialRun,ReviewDecision } from "../schema";
import { hasValidIntegrity,replayFinancialReview,withFinancialRunIntegrity } from "../run";
import type { FinancialRunRepository } from "./contracts";
import { PersistenceConflictError } from "./contracts";
import { analyzeValidatedIncomeStatement } from "../analysis";
import { createFinancialReportPayload, renderFinancialReportPdf, safeReportFilename } from "../report";
export const validatedSnapshotIdentity=(run:FinancialRun)=>createHash("sha256").update(JSON.stringify({schemaVersion:run.schemaVersion,runId:run.runId,revision:run.revision??1,selectedStatement:run.source.selectedSection,periods:run.periods,values:run.values,currency:run.currency,unitScale:run.unitScale,evidence:run.evidence,controls:run.controls,validationSummary:run.validationSummary})).digest("hex");
const snapshot=(run:FinancialRun,actor:string)=>{const payload={schemaVersion:run.schemaVersion,runId:run.runId,revision:run.revision??1,selectedStatement:run.source.selectedSection,periods:run.periods,values:run.values,currency:run.currency,unitScale:run.unitScale,evidence:run.evidence,reviewTasks:run.reviewTasks.filter(t=>t.state==="resolved"),controls:run.controls,validationSummary:run.validationSummary,validatedAt:new Date().toISOString(),validatedBy:actor};return{...payload,integrityHash:validatedSnapshotIdentity(run)}};
export type AnalysisIdentity={revision:number;selectedStatement:string;snapshotHash:string;schemaVersion:string};
export class FinancialRunService{constructor(private repository:FinancialRunRepository){}
 async create(actor:string,run:FinancialRun,file:{size:number;fingerprint:string}){const now=new Date().toISOString();const durable={...run,sessionScoped:false,source:{...run.source,fileSize:file.size,documentFingerprint:file.fingerprint},revision:1,createdAt:now,updatedAt:now,validatedAt:run.status==="validated"?now:run.validatedAt,lastCompletedStage:run.workflow.filter(x=>x.state==="completed").at(-1)?.id};withFinancialRunIntegrity(durable);return this.repository.create(actor,durable,{type:"run_created",after:{status:durable.status,filename:durable.source.filename}})}
 list(actor:string){return this.repository.list(actor)} get(actor:string,id:string){return this.repository.get(actor,id)}
 async analyze(actor:string,id:string,identity:AnalysisIdentity){const run=await this.owned(actor,id);this.verifyAnalysisIdentity(run,identity);if(!hasValidIntegrity(run))throw new Error("RUN_INTEGRITY_INVALID");return analyzeValidatedIncomeStatement(run,undefined,run.integrity)}
 async report(actor:string,id:string,identityOrNow:AnalysisIdentity|string,now?:string){const run=await this.owned(actor,id);const identity=typeof identityOrNow==="string"?{revision:run.revision??1,selectedStatement:run.source.selectedSection??"",snapshotHash:run.integrity,schemaVersion:run.schemaVersion}:identityOrNow;const generatedAt=typeof identityOrNow==="string"?identityOrNow:now;this.verifyAnalysisIdentity(run,identity);if(!hasValidIntegrity(run))throw new Error("RUN_INTEGRITY_INVALID");const analysis=analyzeValidatedIncomeStatement(run,generatedAt,run.integrity);const report=createFinancialReportPayload(run,analysis,generatedAt);return{bytes:renderFinancialReportPdf(report),filename:safeReportFilename(run.source.filename),report}}
 async review(actor:string,id:string,expectedRevision:number,decision:ReviewDecision){const current=await this.owned(actor,id);this.writable(current,expectedRevision);const updated=replayFinancialReview(current,decision);updated.revision=expectedRevision+1;withFinancialRunIntegrity(updated);const event=decision.action==="remap"?"row_remapped":decision.action==="reject"?"review_decision_rejected":"review_decision_accepted";return this.repository.update(actor,updated,expectedRevision,{type:event,before:{taskId:decision.taskId},after:{action:decision.action,concept:decision.concept}},updated.status==="validated"?snapshot(updated,actor):undefined)}
 async archive(actor:string,id:string,expectedRevision:number){const current=await this.owned(actor,id);this.writable(current,expectedRevision);const updated={...current,status:"archived" as const,revision:expectedRevision+1};withFinancialRunIntegrity(updated);return this.repository.update(actor,updated,expectedRevision,{type:"run_archived",before:{status:current.status},after:{status:"archived"}})}
 async revise(actor:string,id:string,expectedRevision:number){const current=await this.owned(actor,id);if(current.status!=="validated"||current.revision!==expectedRevision)throw new Error("Only the current validated revision can be revised");const copy={...current,runId:randomUUID(),status:"review_required" as const,revision:1,parentRunId:current.runId,parentRevision:current.revision,validatedAt:null,createdAt:undefined,updatedAt:undefined,auditEvents:undefined};withFinancialRunIntegrity(copy);return this.repository.create(actor,copy,{type:"revision_created",before:{parentRunId:id,parentRevision:expectedRevision},after:{runId:copy.runId}})}
 private async owned(actor:string,id:string){const run=await this.repository.get(actor,id);if(!run)throw new Error("RUN_NOT_FOUND");return run}private verifyAnalysisIdentity(run:FinancialRun,identity:AnalysisIdentity){if(run.status!=="validated"||run.readiness.status!=="validated")throw new Error("ANALYSIS_REQUIRES_VALIDATED_RUN");if(run.revision!==identity.revision||run.source.selectedSection!==identity.selectedStatement||run.schemaVersion!==identity.schemaVersion||run.integrity!==identity.snapshotHash)throw new Error("STALE_ANALYSIS_IDENTITY")}private writable(run:FinancialRun,revision:number){if(run.status==="archived"||run.status==="validated")throw new Error("RUN_READ_ONLY");if(run.revision!==revision)throw new PersistenceConflictError("Stale run revision")}}
