import Link from "next/link";
import { DecisionImplication, KeyObservation, ResourceFigure, ResourceTable } from "./ResourceElements";
import { workingCapitalModel as model, workingCapitalResults as results } from "./working-capital-model";
import styles from "./resources.module.css";

const millions = (value: number) => `€${(value / 1_000_000).toFixed(2)}m`;
const thousands = (value: number) => `€${(value / 1_000).toFixed(1)}k`;

export const workingCapitalSections = [
  { id: "operating-system", label: "Working capital follows operations" },
  { id: "framework-02", label: "Entimema Framework 02" },
  { id: "three-engines", label: "The three operating engines" },
  { id: "measurement", label: "CCC and the illustrative model" },
  { id: "cash-release", label: "The €1.48m scenario" },
  { id: "drivers", label: "From KPI to action" },
  { id: "financing", label: "Financing and growth" },
  { id: "principles", label: "Trade-offs and limitations" },
] as const;

const engines = [
  ["Receivables engine", "Commercial policy", "Customer mix", "Terms", "Invoicing", "Collection", "Overdue", "Cash"],
  ["Inventory engine", "Demand", "Procurement", "Planning", "Raw materials", "WIP", "Finished goods", "Sales"],
  ["Payables engine", "Procurement", "Supplier mix", "Terms", "Invoice timing", "Scheduling", "Cash outflow"],
] as const;

export default function WorkingCapitalArticle() {
  return <>
    <p className={styles.leadParagraph}>Working capital is visible on the balance sheet, but it is produced in the operating system. Commercial terms become receivables. Procurement and production choices become inventory. Supplier agreements and payment execution become payables. Together, those positions determine how much cash the operating cycle absorbs and how much financing the organisation requires.</p>
    <p>That makes working capital more than a collection of accounts or a target for three day-based KPIs. The accounting view identifies the positions that exist. An operating view traces why they exist, who influences them and what can responsibly change them. The two views answer different questions and must remain reconciled.</p>
    <KeyObservation>Working-capital optimisation becomes decision-useful when management can trace KPI → driver → process → owner → action.</KeyObservation>

    <section id="operating-system">
      <h2>Working capital follows the operating system</h2>
      <p>Receivables, inventory and payables are financial positions generated by processes. A receivable may reflect a deliberate commercial term, delayed invoicing, a disputed invoice or overdue collection. Inventory may be strategic raw-material cover, work trapped at a bottleneck, or finished goods built ahead of demand. A payable may reflect negotiated terms, invoice timing, deliberate scheduling or an overdue liability. The balance-sheet line alone does not distinguish these mechanisms.</p>
      <p>This is why the same aggregate KPI can describe different operating realities. Sixty days of sales outstanding generated by a customer portfolio on contractual 60-day terms is not equivalent to 30-day terms plus 30 days of overdue collection. The numerical result is similar; the commercial exposure, process failure and appropriate action are not.</p>
      <p>Working-capital positions also move with scale and timing. A business can improve collection execution while period-end receivables rise because sales grew rapidly near the reporting date. Inventory days can decline while absolute inventory increases to support a larger operation. Management therefore needs both absolute positions and normalised measures, supported by bridges that separate volume, mix, timing and process effects.</p>
      <ResourceTable caption="Complementary views of working capital" headers={["Balance-sheet view", "Operating / management view"]} rows={[
        ["Which receivable, inventory and payable positions exist?", "Which process and driver generated each position?"],
        ["What is the period-end balance?", "How did timing, volume, mix and execution move the balance?"],
        ["How is the position classified and measured?", "Who owns the controllable mechanism?"],
        ["What is net working capital?", "What cash and financing effect follows from a change?"],
      ]} />
      <p>Conventional accounting measures are not incorrect because they are aggregated. They serve reporting, control and stewardship. The management layer adds causal decomposition for decisions; it does not redefine the accounts or create an alternative statutory balance sheet.</p>
    </section>

    <section id="framework-02">
      <h2>Entimema Framework 02: Working Capital System</h2>
      <p>Framework 02 has two dimensions. The first follows three operating engines into operating working capital, cash conversion, financing requirement and management decision. The second tests an intervention through operating driver, working-capital position, cash effect, financing effect and decision. This prevents the framework from becoming three KPI boxes.</p>
      <ResourceFigure label="Entimema Framework 02. Receivables, inventory and payables engines converge into operating working capital, cash conversion, financing requirement and management decision. A second dimension connects driver, position, cash, financing and decision." caption="Framework 02 connects reported positions to their operating causes. Its drivers and ownership must be adapted to the organisation, data and decision context.">
        <div className={styles.framework02}>
          <div className={styles.engineGrid}>{engines.map(([name, ...steps]) => <article key={name}><strong>{name}</strong><div>{steps.map((step) => <span key={step}>{step}</span>)}</div></article>)}</div>
          <div className={styles.convergence}><span>OPERATING WORKING CAPITAL</span><b>↓</b><span>CASH CONVERSION</span><b>↓</b><span>FINANCING REQUIREMENT</span><b>↓</b><span>MANAGEMENT DECISION</span></div>
          <div className={styles.wcDecisionFlow}>{["Operating driver", "Position", "Cash effect", "Financing effect", "Decision"].map((step) => <span key={step}>{step}</span>)}</div>
        </div>
      </ResourceFigure>
      <p>For example, extending customer payment terms by ten days increases receivables, reduces available cash, increases the financing requirement and exposes a commercial or credit-policy decision. The arithmetic is only one part of the chain. Management must still ask which customers are affected, what commercial value the concession creates, who approved it and whether the financing consequence is acceptable.</p>
      <p>Ownership in this framework is deliberately distributed. Finance can reconcile positions, quantify cash effects and make trade-offs visible, but it does not independently control every driver. Commercial teams shape customer terms; operations and supply-chain teams shape inventory; procurement shapes supplier economics; shared-service and treasury processes influence execution timing. A credible working-capital model therefore assigns driver ownership without pretending the balance-sheet line belongs to one function.</p>
    </section>

    <section id="three-engines">
      <h2>Three engines create the reported position</h2>
      <h3>Receivables: one DSO, different mechanisms</h3>
      <p>DSO can move because sales are growing, customer mix changes, contractual terms lengthen, invoices are raised later, billing quality creates disputes, collections slow or overdue balances accumulate. Not every organisation has every mechanism, and their materiality changes over time. The analytical task is to reconcile the aggregate result to the mechanisms that actually operate.</p>
      <p>A policy response aimed at collections will not correct delayed invoicing. Tighter credit control may not address a deliberate commercial-term decision. A broad DSO target can therefore create pressure without identifying a responsible action. Cohorts by invoice month, contractual due date, customer segment and overdue status often provide more decision information than one period-end average.</p>
      <p>Sales growth creates another interpretation problem. When recent sales carry a different customer or term mix, a simple annual-sales denominator can hide the transition. Management may need invoice-level ageing, weighted contractual terms and a bridge between not-yet-due, overdue and disputed positions. That decomposition makes clear whether cash is tied up by agreed commercial policy or by execution outside policy.</p>
      <h3>Inventory is not one operating phenomenon</h3>
      <p>Raw materials, work in progress and finished goods occupy different points in the operating flow. Raw-material holdings may respond to supplier lead time, batch economics, commodity exposure or safety-stock policy. WIP may reflect production cycle, queue time, yield or a bottleneck. Finished goods may reflect service policy, demand expectations, forecast error, campaign production or slow-moving stock.</p>
      <p>Two businesses can report the same total inventory and face different risks. Reducing strategic material cover may impair continuity, while reducing avoidable WIP could release cash and improve flow. Finished-goods accumulation caused by forecast bias requires a different owner and action from WIP accumulated before a constrained production stage. Article 01&apos;s <Link href="/resources/building-a-manufacturing-cost-architecture">manufacturing cost architecture</Link> provides the complementary production-stage view.</p>
      <p>Inventory analysis should also preserve age, movement and future-use signals. A stable DIO can conceal a growing slow-moving tail offset by faster movement elsewhere. Conversely, a temporary increase may be economically rational when a known shutdown, long supplier lead time or seasonal demand peak is approaching. The model should expose these conditions rather than applying one target indiscriminately.</p>
      <h3>Payables: higher DPO is not always better</h3>
      <p>Payables arise from procurement, supplier mix, contractual terms, invoice receipt and approval, and payment scheduling. A deliberate extension negotiated with a supplier is different from an overdue invoice caused by a blocked approval. Both may increase reported DPO; only one may represent an intentional financing choice.</p>
      <p>Mechanically delaying payment can affect supplier pricing, reliability, negotiating position, credit terms and access to constrained supply. It may also transfer financing pressure to a strategically important supplier. Working-capital optimisation is therefore not the maximisation of DPO and minimisation of DSO and DIO at any cost.</p>
      <p>A useful payable bridge distinguishes contractual from actual payment timing and identifies why the difference exists. Early payment may be justified by a discount or supply priority. Late payment may indicate a control issue rather than negotiating strength. Supplier segmentation is therefore relevant: the financing value of a term change must be considered beside supplier dependency, commercial cost and continuity risk.</p>
    </section>

    <section id="measurement">
      <h2>The cash conversion cycle is a measurement layer</h2>
      <p>The conventional relationship <strong>CCC = DSO + DIO − DPO</strong> provides a useful summary of the approximate time for which cash is committed to the operating cycle. In the illustrative model, DSO of {model.current.dso} days plus DIO of {model.current.dio} days less DPO of {model.current.dpo} days produces a CCC of {results.currentCcc} days.</p>
      <p>CCC does not by itself identify which process caused the result, which driver changed, who owns it or which action is economically appropriate. It is the measurement layer. Framework 02 adds explanatory and decision layers.</p>
      <ResourceTable caption="Illustrative operating working-capital position" headers={["Position", "Simplified calculation", "Approximate value"]} rows={[
        ["Receivables", `€36.0m × 60 / 365`, millions(results.receivables)], ["Inventory", `€25.2m × 75 / 365`, millions(results.inventory)], ["Payables", `€25.2m × 45 / 365`, `(${millions(results.payables)})`], ["Operating working capital", "Receivables + inventory − payables", millions(results.operatingWorkingCapital)],
      ]} />
      <p>The model is hypothetical and does not represent Entimema or a client. It assumes annual revenue of €36.0m and annual COGS of €25.2m, applies 365-day approximations and uses revenue for receivables and COGS for both inventory and payables. It is a simplified operating model, not a universal statutory working-capital formula.</p>
      <p>The operating position of approximately {millions(results.operatingWorkingCapital)} is an analytical estimate, not a substitute for ledger balances. Its value is that the day assumptions and denominators are explicit. Management can reconcile the estimate, test sensitivity and replace broad annual inputs with monthly, weekly or transaction-level data where seasonality or volatility makes the approximation unreliable.</p>
    </section>

    <section id="cash-release">
      <h2>An €1.48m cash release—and the conditions around it</h2>
      <p>The approved scenario reduces DSO from 60 to 52 days and DIO from 75 to 65 days, with DPO unchanged at 45 days. CCC moves from 90 to 72 days. Eight fewer receivables days release approximately {millions(results.receivablesRelease)}; ten fewer inventory days release approximately {millions(results.inventoryRelease)}. The combined illustrative release is {millions(results.totalCashRelease)}.</p>
      <ResourceFigure label="Illustrative working-capital scenario. Current DSO 60, DIO 75, DPO 45 and CCC 90 move to DSO 52, DIO 65, DPO 45 and CCC 72. Receivables release 0.79 million euros plus inventory release 0.69 million euros equals total cash release 1.48 million euros." caption="Illustrative model. The scenario assumes improvements can be achieved without damaging revenue, customer service, supply continuity or operating resilience.">
        <div className={styles.cashReleaseVisual}>
          <span>ILLUSTRATIVE MODEL</span>
          <div className={styles.cycleComparison}><article><small>CURRENT</small><strong>CCC {results.currentCcc}</strong><p>DSO 60 · DIO 75 · DPO 45</p></article><b>→</b><article><small>SCENARIO</small><strong>CCC {results.scenarioCcc}</strong><p>DSO 52 · DIO 65 · DPO 45</p></article></div>
          <div className={styles.releaseComponents}><article><small>RECEIVABLES RELEASE</small><strong>{millions(results.receivablesRelease)}</strong></article><b>+</b><article><small>INVENTORY RELEASE</small><strong>{millions(results.inventoryRelease)}</strong></article></div>
          <div className={styles.releaseTotal}><small>TOTAL CASH RELEASE</small><strong>{millions(results.totalCashRelease)}</strong></div>
        </div>
      </ResourceFigure>
      <p>The scenario is not a promise. It assumes the day improvements can be sustained without weakening commercial competitiveness, production availability, service performance or supply resilience. Cash release describes liquidity capacity created by a lower operating position. It is not automatically recurring accounting profit.</p>
      <p>Timing matters as well. A permanent structural reduction can create sustained liquidity capacity; a temporary period-end action may reverse immediately. Management should distinguish recurring process change from cut-off timing, one-off collection campaigns, deferred purchasing and delayed payment. The scenario becomes credible only when the path, implementation period and persistence of each component are visible.</p>
    </section>

    <section id="drivers">
      <h2>The real question is how the release is achieved</h2>
      <p>A target to reduce DSO by eight days remains incomplete until it is decomposed. Contractual terms may sit with commercial policy; invoicing delay with order-to-cash execution; collection delay with credit control; disputes with billing quality and operational delivery; customer mix with commercial strategy. Each mechanism has a different owner, constraint and action.</p>
      <p>The same discipline applies to DIO. Safety stock, purchasing batch size, supplier lead time, production cycle, WIP, forecast error and slow-moving finished goods cannot be corrected by one generic inventory instruction. A target imposed at aggregate level may cause a local team to reduce the wrong stock and increase risk elsewhere.</p>
      <p>The owner must also possess a real decision right. Naming “operations” beside DIO is too broad if planners set replenishment parameters, procurement negotiates batch sizes and plant teams control cycle time. Driver-level ownership makes the action testable: which parameter changes, who authorises it, what leading indicator confirms execution and which risk boundary stops the intervention?</p>
      <ResourceFigure label="Two examples of KPI-to-action architecture. DSO moves through invoicing delay, order-to-cash, billing owner and invoice-release control. DIO moves through work-in-progress accumulation, production flow, operations owner and bottleneck response." caption="A KPI becomes actionable only when the driver, process, owner and intervention are explicit enough to test.">
        <div className={styles.kpiAction}><div className={styles.kpiHeaders}>{["KPI", "Driver", "Process", "Owner", "Action"].map((item) => <span key={item}>{item}</span>)}</div><div>{["DSO", "Invoicing delay", "Order-to-cash", "Billing owner", "Release control"].map((item) => <span key={item}>{item}</span>)}</div><div>{["DIO", "WIP accumulation", "Production flow", "Operations", "Bottleneck response"].map((item) => <span key={item}>{item}</span>)}</div></div>
      </ResourceFigure>
      <DecisionImplication>KPI targets without driver decomposition can produce activity without improving the operating system—and can move risk from one function to another.</DecisionImplication>
    </section>

    <section id="financing">
      <h2>Working capital connects operations to financing and strategy</h2>
      <p>At an illustrative annual financing rate of 6%, {millions(results.totalCashRelease)} corresponds to an annual financing effect of approximately {thousands(results.financingEffect)}. The rate is hypothetical, and the amount should not be described automatically as profit or guaranteed savings. The actual effect depends on funding structure, timing, taxes, interest conventions and how the released liquidity is used.</p>
      <p>The more important result is liquidity capacity. Management could potentially allocate approximately €1.48m towards debt reduction, capital expenditure, growth, a liquidity buffer or another capital priority. The operating intervention therefore continues through cash into financing and capital allocation.</p>
      <h3>The growth paradox</h3>
      <p>Growth can consume cash even when revenue and accounting profit increase. More sales may create more receivables; service commitments and production plans may require more inventory; the timing of supplier funding may not expand at the same rate. Profitable growth can therefore create a working-capital financing requirement. A credible <Link href="/services/budgets-and-forecasting">planning and forecasting system</Link> models those balance-sheet and cash mechanics alongside the income statement.</p>
      <p>Where a business needs senior finance leadership to establish ownership, controls and a recurring cash-management rhythm, these mechanics also form part of Entimema&apos;s <Link href="/services/cfo-function">fractional CFO services</Link>.</p>
      <p>This has practical consequences for scenario design. A revenue plan should not translate directly into profit and stop. It should carry customer terms and collection timing into receivables, demand and supply assumptions into inventory, and purchasing terms into payables. The resulting cash curve exposes whether growth can be funded internally, requires facilities or depends on an operating improvement that has not yet been assigned.</p>
    </section>

    <section id="principles">
      <h2>System optimisation requires explicit trade-offs</h2>
      <p>Lower inventory may improve cash but increase service or production risk. Longer supplier terms may improve cash but alter supplier economics and continuity. Tighter customer terms may reduce receivables but weaken commercial competitiveness. The right question is not whether each local KPI can be improved in isolation, but whether the combined operating, cash and risk outcome is better.</p>
      <p>Local optimisation can also move a position rather than remove its cause. Smaller raw-material orders may reduce inventory while increasing freight or stockout exposure. Aggressive collections may accelerate one cohort while damaging renewal economics. Extended supplier terms may improve reported cash temporarily but reappear in higher prices. System optimisation evaluates the full economic consequence and the resilience boundary, not only the balance-sheet movement.</p>
      <div className={styles.principles}>
        <article><span>PRINCIPLE 01</span><h3>Working capital follows operations.</h3><p>Balance-sheet positions emerge from commercial, supply and production processes.</p></article>
        <article><span>PRINCIPLE 02</span><h3>A KPI without its drivers is incomplete.</h3><p>DSO, DIO and DPO show aggregate outcomes, but do not necessarily explain their causes.</p></article>
        <article><span>PRINCIPLE 03</span><h3>Optimisation is a system problem.</h3><p>Locally attractive KPIs can damage the economics or resilience of the overall operating system.</p></article>
      </div>
      <h3>Limitations are part of the model</h3>
      <p>The 365-day approximations simplify seasonality, and average balances may differ materially from period-end positions. Revenue may include VAT or other components depending on source data. Inventory depends on the selected denominator; DPO depends on purchasing or COGS assumptions. Seasonal businesses require more granular modelling, business models differ, and negative working-capital structures exist.</p>
      <p>Working-capital interventions can involve service, commercial and supply-risk trade-offs. A cash release is not automatically recurring profit improvement. Definitions must be reconciled to source data, and scenarios must state timing, ownership, constraints and reversibility.</p>
      <h3>The objective is responsible intervention</h3>
      <p>The objective is not merely to calculate a better DSO, DIO or DPO. It is to understand how operating decisions become balance-sheet positions, how those positions consume or release cash, and where management can intervene responsibly. A working-capital system makes that chain visible—from operations, through cash and financing, to decision.</p>
    </section>
  </>;
}
