from enum import StrEnum


class DialogueReasonCode(StrEnum):
    UNRESOLVED_REFERENCE = "UNRESOLVED_REFERENCE"
    DEFINITION_MISMATCH = "DEFINITION_MISMATCH"
    MATERIAL_AMBIGUITY = "MATERIAL_AMBIGUITY"
    REPAIR_RESOLVED = "REPAIR_RESOLVED"
    REPAIR_UNRESOLVABLE = "REPAIR_UNRESOLVABLE"
    PROBLEM_CONTEXT_SUFFICIENT = "PROBLEM_CONTEXT_SUFFICIENT"
    HYPOTHESIS_ELIGIBLE = "HYPOTHESIS_ELIGIBLE"
    MATERIAL_CONTRADICTION = "MATERIAL_CONTRADICTION"
    CRITICAL_UNKNOWN = "CRITICAL_UNKNOWN"
    HIGH_UNKNOWN = "HIGH_UNKNOWN"
    QUESTION_SELECTED = "QUESTION_SELECTED"
    ROUTING_GATE_PASS = "ROUTING_GATE_PASS"
    ROUTING_GATE_FAIL = "ROUTING_GATE_FAIL"
    FORBIDDEN_INFERENCE = "FORBIDDEN_INFERENCE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
