import { randomUUID } from "node:crypto";
import { AgentError, errorResponse } from "../../../lib/errors";
import { deleteUpload, downloadUpload, issueUpload, verifyReference } from "../../../lib/private-upload";
import { runInspectedDocumentClassifier } from "./run";
import type { AuthorizedActor } from "../../../../lib/execution-auth";
import type { ExecutionRateLimiter } from "../../../lib/rate-limit";

type Dependencies={authorize:()=>Promise<AuthorizedActor>;rateLimiter:ExecutionRateLimiter;classifier?:typeof runInspectedDocumentClassifier;logger?:(level:"info"|"error",entry:Record<string,unknown>)=>void};
async function json(request:Request){if(!(request.headers.get("content-type")??"").toLowerCase().startsWith("application/json"))throw new AgentError("FILE_MISSING",400);try{return await request.json();}catch{throw new AgentError("FILE_MISSING",400);}}
export function createUploadGrantHandler(deps:Pick<Dependencies,"authorize">){return async(request:Request)=>{const runId=randomUUID();try{const actor=await deps.authorize();return Response.json(issueUpload(actor.actorId,await json(request)),{headers:{"Cache-Control":"no-store"}});}catch(error){return errorResponse(error,runId);}};}
export function createDirectRunHandler(deps:Dependencies){return async(request:Request)=>{const runId=randomUUID();let ref:ReturnType<typeof verifyReference>|undefined;try{const actor=await deps.authorize();await deps.rateLimiter.consume(actor.actorId);const body=await json(request) as {upload_reference?:unknown};if(typeof body.upload_reference!=="string")throw new AgentError("UPLOAD_REFERENCE_INVALID",400);ref=verifyReference(body.upload_reference,actor.actorId);const document=await downloadUpload(ref);const result=await (deps.classifier??runInspectedDocumentClassifier)(document);return Response.json({run_id:runId,...result.response},{headers:{"Cache-Control":"no-store"}});}catch(error){return errorResponse(error,runId);}finally{if(ref)try{await deleteUpload(ref);}catch{deps.logger?.("error",{run_id:runId,agent:"document_classifier",event:"temporary_cleanup_failed"});}}};}
export function createUploadDeleteHandler(deps:Pick<Dependencies,"authorize">){return async(request:Request)=>{const runId=randomUUID();try{const actor=await deps.authorize(),body=await json(request) as {upload_reference?:unknown};if(typeof body.upload_reference!=="string")throw new AgentError("UPLOAD_REFERENCE_INVALID",400);await deleteUpload(verifyReference(body.upload_reference,actor.actorId));return new Response(null,{status:204,headers:{"Cache-Control":"no-store"}});}catch(error){return errorResponse(error,runId);}};}
