"""Closed vocabularies used by the runtime domain model."""

from enum import StrEnum


class EpistemicType(StrEnum):
    OBSERVED = "OBSERVED"
    RETRIEVED = "RETRIEVED"
    REPORTED = "REPORTED"
    REPORTED_OBSERVATION = "REPORTED_OBSERVATION"
    CALCULATED = "CALCULATED"
    MODEL_PRODUCED = "MODEL_PRODUCED"
    ASSUMPTION = "ASSUMPTION"
    HYPOTHESIS = "HYPOTHESIS"
    INFERENCE = "INFERENCE"
    DECISION = "DECISION"
    UNKNOWN = "UNKNOWN"
    CONTRADICTED = "CONTRADICTED"


class Materiality(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EpistemicVerdict(StrEnum):
    VALIDATED = "VALIDATED"
    CONDITIONALLY_VALID = "CONDITIONALLY_VALID"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CONTRADICTED = "CONTRADICTED"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    FORBIDDEN_INFERENCE = "FORBIDDEN_INFERENCE"
    TRACEABILITY_FAILURE = "TRACEABILITY_FAILURE"


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class WorkspacePhase(StrEnum):
    """Where the workspace is; deliberately independent of readiness."""

    INTAKE = "INTAKE"
    PROBLEM_DISCOVERY = "PROBLEM_DISCOVERY"
    EVIDENCE_GATHERING = "EVIDENCE_GATHERING"
    EPISTEMIC_REVIEW = "EPISTEMIC_REVIEW"
    ANALYSIS = "ANALYSIS"
    DECISION_SUPPORT = "DECISION_SUPPORT"
    CLOSED = "CLOSED"


class DecisionReadiness(StrEnum):
    BLOCKED = "BLOCKED"
    FORMATION_READY = "FORMATION_READY"
    ANALYSIS_READY = "ANALYSIS_READY"
    ANALYSIS_IN_PROGRESS = "ANALYSIS_IN_PROGRESS"
    DECISION_SUPPORT_READY = "DECISION_SUPPORT_READY"
