"""Closed vocabularies used by the runtime domain model."""

from enum import StrEnum


class EpistemicType(StrEnum):
    OBSERVED = "OBSERVED"
    RETRIEVED = "RETRIEVED"
    REPORTED = "REPORTED"
    REPORTED_OBSERVATION = "REPORTED_OBSERVATION"
    CALCULATED = "CALCULATED"
    MODEL_PRODUCED = "MODEL_PRODUCED"
    ASSUMPTION = "ASSUMPTION"
    HYPOTHESIS = "HYPOTHESIS"
    INFERENCE = "INFERENCE"
    DECISION = "DECISION"
    UNKNOWN = "UNKNOWN"
    CONTRADICTED = "CONTRADICTED"


class Materiality(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EpistemicVerdict(StrEnum):
    VALIDATED = "VALIDATED"
    CONDITIONALLY_VALID = "CONDITIONALLY_VALID"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CONTRADICTED = "CONTRADICTED"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    FORBIDDEN_INFERENCE = "FORBIDDEN_INFERENCE"
    TRACEABILITY_FAILURE = "TRACEABILITY_FAILURE"


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
