"use client";

import { useEffect, useRef } from "react";

const financeItems = ["Мениджърска отчетност","Финансово моделиране","Бюджетиране и прогнозиране","Управление чрез KPI","Парични потоци и ликвидност","Финансов контрол","Управление на разходите","Външен финансов директор"];
const riskItems = ["Апликационен скоринг","AI системи за решения","Поведенчески скоринг","Мониторинг на портфейли","PD / LGD / EAD модели","Стрес тестове","IFRS 9 модели","Сценариен анализ"];

function FinancePreview(){return <div className="system-preview system-preview--finance" aria-hidden="true"><div className="system-preview__top"><span>Finance OS</span><b>Forecast</b></div><div className="system-preview__metric"><strong>€12.8M</strong><small>Next 12 months</small></div><svg viewBox="0 0 360 120"><path className="grid" d="M0 30h360M0 60h360M0 90h360"/><path className="area" d="M0 110 50 91 100 95 150 67 205 74 250 42 305 50 360 20V120H0Z"/><path className="line" d="M0 110 50 91 100 95 150 67 205 74 250 42 305 50 360 20"/></svg></div>}
function RiskPreview(){return <div className="system-preview system-preview--risk" aria-hidden="true"><div className="system-preview__top"><span>Risk OS</span><b>Live decision</b></div><div className="system-preview__decision"><div><small>Applicant #94831</small><strong>82 / 100</strong></div><em>APPROVE</em></div><div className="system-preview__factors"><span>Income stability <b>High</b></span><span>Debt service <b>Healthy</b></span><span>Behaviour <b>Positive</b></span></div></div>}

function SystemCard({kind,title,description,items}:{kind:"finance"|"risk";title:string;description:string;items:string[]}){return <article className={`approach-card approach-card--${kind}`}><div className="approach-card__topline"><span>{kind==="finance"?"FINANCE OPERATING SYSTEM":"DECISION INTELLIGENCE"}</span><i/></div><div className="approach-card__body"><div className="approach-card__copy"><h3>{title}</h3><p>{description}</p></div>{kind==="finance"?<FinancePreview/>:<RiskPreview/>}</div><div className="approach-card__items">{items.map((label)=><div className="approach-card__item" key={label}><span aria-hidden="true"/><b>{label}</b></div>)}</div><a className="approach-card__button" href={kind==="finance"?"#financial-architecture":"#credit-risk"}>{kind==="finance"?"Разгледайте финансовата архитектура":"Разгледайте решенията"}<span>↗</span></a></article>}

export default function ApproachSection(){const ref=useRef<HTMLElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;const io=new IntersectionObserver(([e])=>{if(e.isIntersecting){el.classList.add("is-visible");io.disconnect();}},{threshold:.18});io.observe(el);return()=>io.disconnect();},[]);return <section className="approach-section" id="about" ref={ref}><div className="site-container approach-section__inner"><div className="approach-section__intro reveal reveal--1"><h2>Финанси и риск,<br/><em>мислени като една система.</em></h2></div><p className="approach-section__lead reveal reveal--2">Използваме единна методология за изграждане на финансови системи, модели за кредитен риск и AI решения. Независимо от приложението, принципите остават едни и същи.</p><div className="approach-section__cards reveal reveal--3"><SystemCard kind="finance" title="Финансова архитектура" description="Проектираме финансови системи, които превръщат данните в ясни управленски решения и растат заедно с бизнеса." items={financeItems}/><SystemCard kind="risk" title="Кредитен риск" description="Разработваме интелигентни системи за оценка, мониторинг и автоматизация на кредитния риск." items={riskItems}/></div></div></section>}
