import Link from "next/link";

const services = [
  { number:"01", title:"Финансова архитектура", description:"Проектираме финансови системи, които превръщат данните в управленски решения, а стратегията – в изпълнение.", cta:"Вижте подхода", href:"/services/financial-architecture", preview:"finance" },
  { number:"02", title:"Управление на риска", description:"Изграждаме модели и системи за оценка, мониторинг и управление на риска за банки и небанкови финансови институции.", cta:"Вижте подхода", href:"/services/risk-management", preview:"risk" },
  { number:"03", title:"Данни, AI и автоматизация", description:"Свързваме данни, изкуствен интелект и автоматизация в единна среда за по-бързи и по-добри управленски решения.", cta:"Вижте подхода", href:"/services/data-ai-automation", preview:"ai" },
  { number:"04", title:"Финансова трансформация", description:"Трансформираме финансовата функция чрез процеси, технологии и управленски модели, които повишават ефективността.", cta:"Разгледайте трансформацията", href:"/services/finance-transformation", preview:"workflow" },
  { number:"05", title:"CFO функция", description:"Изграждаме или поемаме CFO функцията като стратегически партньор на бизнеса – от планирането до управленските решения.", cta:"Разгледайте CFO услугите", href:"/services/cfo", preview:"cfo" },
  { number:"06", title:"Финансови AI агенти", description:"Разработваме AI агенти за финансови задачи, които изпълняват повтаряеми процеси във финансовия екип.", cta:"Разгледайте AI агентите", href:"/services/financial-ai-agents", preview:"agent", badge:"НОВО" },
] as const;

type Preview = typeof services[number]["preview"];

function ProductPreview({ type }: { type: Preview }) {
  if (type === "finance") return <div className="product-preview product-preview--finance" aria-hidden="true"><div className="preview-head"><span>Управленска прогноза</span><b>Q3</b></div><div className="metric-row"><strong>€12.8M</strong><small>Прогноза за приходите</small></div><svg viewBox="0 0 280 92"><path className="grid" d="M0 23h280M0 46h280M0 69h280"/><path className="area" d="M0 82 36 67 72 72 110 46 146 54 182 31 220 38 280 14V92H0Z"/><path className="line" d="M0 82 36 67 72 72 110 46 146 54 182 31 220 38 280 14"/></svg></div>;
  if (type === "risk") return <div className="product-preview product-preview--risk" aria-hidden="true"><div className="preview-head"><span>Decision Engine</span><b>Активен</b></div><div className="risk-score"><div><small>Заявление</small><strong>#94831</strong></div><em>82</em></div><div className="decision-bar"><span>Одобрение</span><i/><span>Преглед</span><i/><span>Отказ</span></div></div>;
  if (type === "ai") return <div className="product-preview product-preview--ai" aria-hidden="true"><div className="preview-head"><span>Оркестрация на данни</span><b>7 процеса</b></div><div className="flow-row"><span>ERP</span><i>→</i><span>AI слой</span><i>→</i><span>Решение</span></div><div className="flow-status"><i/><span>Моделите са синхронизирани</span><strong>99.7%</strong></div></div>;
  if (type === "workflow") return <div className="product-preview product-preview--workflow" aria-hidden="true"><div className="preview-head"><span>Карта на трансформацията</span><b>Етап 2</b></div><div className="workflow-line"><span>Диагностика</span><i/><span>Проектиране</span><i/><span>Внедряване</span><i/><span>Мащабиране</span></div><div className="progress"><span style={{width:"68%"}}/></div></div>;
  if (type === "cfo") return <div className="product-preview product-preview--cfo" aria-hidden="true"><div className="preview-head"><span>CFO табло</span><b>Днес</b></div><div className="cockpit-grid"><div><small>Парични средства</small><strong>€3.4M</strong></div><div><small>EBITDA</small><strong>18.6%</strong></div><div><small>Финансов хоризонт</small><strong>14 м.</strong></div></div><div className="signal-row"><span/><p>3 решения изискват внимание</p></div></div>;
  return <div className="product-preview product-preview--agent" aria-hidden="true"><div className="preview-head"><span>Финансов агент</span><b>Активен</b></div><div className="agent-prompt">Анализирай отклонението в маржа по продукти и обясни трите основни фактора.</div><div className="agent-result"><i/><span>Анализът е завършен</span><strong>12s</strong></div></div>;
}

export default function ServicesSection() {
  return <section className="services-hero" aria-labelledby="services-title"><div className="site-container services-hero__inner"><div className="services-hero__heading"><h1 id="services-title">Превръщаме<br/><em>сложността в яснота.</em></h1></div><p className="services-hero__lead">Всяка област носи собствена стойност.<br/>Заедно изграждат интегрирана<br/>управленска архитектура.</p><div className="services-grid">{services.map((service)=><article className="service-card service-card--product" key={service.number}>{"badge" in service && service.badge ? <span className="service-card__badge">{service.badge}</span> : null}<div className="service-card__meta"><span>{service.number}</span><small>СИСТЕМА НА ENTIMEMA</small></div><ProductPreview type={service.preview}/><div className="service-card__copy"><h2>{service.title}</h2><p>{service.description}</p></div><Link className="service-card__link" href={service.href}><span>{service.cta}</span><b aria-hidden="true">↗</b></Link></article>)}</div></div></section>;
}
