import Link from "next/link";

const services = [
  { number: "01", title: "CFO Advisory", description: "Build the financial structure, management information and decision routines the business needs as it grows.", cta: "Explore CFO Advisory", href: "/services/cfo-function", preview: "finance" },
  { number: "02", title: "Planning & Forecasting", description: "Connect operational drivers, financial forecasts, scenarios and cash decisions in one planning system.", cta: "Explore Planning & Forecasting", href: "/services/budgets-and-forecasting", preview: "workflow" },
  { number: "03", title: "Management Reporting", description: "Design management information around the KPIs, operating drivers and decisions that matter.", cta: "Explore Management Reporting", href: "/services/management-reporting", preview: "cfo" },
  { number: "04", title: "Financial Data", description: "Create one reliable financial data foundation across ERP, reporting, planning and analytics.", cta: "Explore Financial Data", href: "/services/financial-data", preview: "ai" },
  { number: "05", title: "Credit Risk", description: "Connect risk models, policy, portfolio behaviour and decision logic across the credit lifecycle.", cta: "Explore Credit Risk", href: "/services/credit-risk", preview: "risk" },
  { number: "06", title: "Finance AI Agents", description: "Give controlled AI agents defined roles across recurring finance processes, with trusted data and human oversight.", cta: "Explore Finance AI Agents", href: "/services/financial-ai-agents", preview: "agent", badge: "NEW" },
] as const;

type Preview = typeof services[number]["preview"];

function ProductPreview({ type }: { type: Preview }) {
  if (type === "finance") return <div className="product-preview product-preview--finance" aria-hidden="true"><div className="preview-head"><span>Management forecast</span><b>Q3</b></div><div className="metric-row"><strong>€12.8M</strong><small>Revenue forecast</small></div><svg viewBox="0 0 280 92"><path className="grid" d="M0 23h280M0 46h280M0 69h280"/><path className="area" d="M0 82 36 67 72 72 110 46 146 54 182 31 220 38 280 14V92H0Z"/><path className="line" d="M0 82 36 67 72 72 110 46 146 54 182 31 220 38 280 14"/></svg></div>;
  if (type === "risk") return <div className="product-preview product-preview--risk" aria-hidden="true"><div className="preview-head"><span>Decision Engine</span><b>Illustrative</b></div><div className="risk-score"><div><small>Application</small><strong>#94831</strong></div><em>82</em></div><div className="decision-bar"><span>Approve</span><i/><span>Review</span><i/><span>Decline</span></div></div>;
  if (type === "ai") return <div className="product-preview product-preview--ai" aria-hidden="true"><div className="preview-head"><span>Data orchestration</span><b>7 processes</b></div><div className="flow-row"><span>ERP</span><i>→</i><span>Model</span><i>→</i><span>Decision</span></div><div className="flow-status"><i/><span>Models synchronised</span><strong>99.7%</strong></div></div>;
  if (type === "workflow") return <div className="product-preview product-preview--workflow" aria-hidden="true"><div className="preview-head"><span>Planning cycle</span><b>Stage 2</b></div><div className="workflow-line"><span>Diagnose</span><i/><span>Model</span><i/><span>Implement</span><i/><span>Evolve</span></div><div className="progress"><span style={{ width: "68%" }}/></div></div>;
  if (type === "cfo") return <div className="product-preview product-preview--cfo" aria-hidden="true"><div className="preview-head"><span>Management view</span><b>Example</b></div><div className="cockpit-grid"><div><small>Cash</small><strong>€3.4M</strong></div><div><small>EBITDA</small><strong>18.6%</strong></div><div><small>Forecast horizon</small><strong>14 mo.</strong></div></div><div className="signal-row"><span/><p>3 decisions require attention</p></div></div>;
  return <div className="product-preview product-preview--agent" aria-hidden="true"><div className="preview-head"><span>Finance agent</span><b>Illustrative</b></div><div className="agent-prompt">Analyse the product margin variance and explain the three main drivers.</div><div className="agent-result"><i/><span>Analysis complete</span><strong>12s</strong></div></div>;
}

export default function ServicesSection() {
  return <section className="services-hero" aria-labelledby="services-title"><div className="site-container services-hero__inner"><div className="services-hero__heading"><h1 id="services-title">Turn complexity<br/><em>into decision architecture.</em></h1></div><p className="services-hero__lead">Each discipline solves a different part of the problem.<br/>Together they create one connected<br/>management architecture.</p><div className="services-grid">{services.map((service) => <article className="service-card service-card--product" key={service.number}>{"badge" in service && service.badge ? <span className="service-card__badge">{service.badge}</span> : null}<div className="service-card__meta"><span>{service.number}</span><small>ENTIMEMA SYSTEM</small></div><ProductPreview type={service.preview}/><div className="service-card__copy"><h2>{service.title}</h2><p>{service.description}</p></div><Link className="service-card__link" href={service.href}><span>{service.cta}</span><b aria-hidden="true">↗</b></Link></article>)}</div></div></section>;
}
