import type { AgentMarkName } from "./AgentMarks";

export const agentCategories = ["All", "Onboarding", "Finance", "Credit", "Risk & Compliance"] as const;
export type AgentCategory = Exclude<(typeof agentCategories)[number], "All">;
type GlyphTone = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
export type AgentDefinition = { id: string; slug: string; name: string; description: string; href: string; categories: readonly AgentCategory[]; mark: AgentMarkName; tone: GlyphTone; signatureImage?: string; operation: string; mechanism: string; metaphor: string };

// Agent -> decision problem -> analytical mechanism -> visual metaphor -> composition.
// This is the acceptance record for deliberate EAM assignment, not user-facing copy.
export const agents: readonly AgentDefinition[] = [
  { id: "application-completeness", slug: "application-completeness", name: "Application Completeness Agent", description: "Assess application submissions for missing documents, incomplete fields and critical data gaps before downstream underwriting or credit analysis begins.", href: "/services/risk-ai-agents", categories: ["Onboarding", "Credit"], mark: "closure", tone: 1, operation: "Resolve required evidence into a complete state", mechanism: "Evidence positions converge on the remaining gap", metaphor: "Incomplete architecture closing around a central chamber" },
  { id: "document-classification", slug: "document-classification", name: "Document Classification Agent", description: "Classify incoming documents and content into the correct operational categories, routing information into the structures required for faster and more consistent processing.", href: "/services/risk-ai-agents", categories: ["Onboarding", "Finance", "Credit"], mark: "classification", tone: 4, operation: "Assign unstructured evidence to a defined state", mechanism: "Observations cross a classification boundary into ordered regions", metaphor: "Information field resolving across a decision boundary" },
  { id: "financial-statement-extraction", slug: "financial-statement-extraction", name: "Financial Statement Extraction Agent", description: "Extract and structure key financial data from statements and supporting documents, reducing manual processing and preparing reliable inputs for downstream analysis.", href: "/services/financial-ai-agents", categories: ["Finance", "Credit"], mark: "extraction", tone: 7, operation: "Select structured variables from dense source information", mechanism: "Candidate values pass through a narrow analytical aperture", metaphor: "Dense source field opening into three clean terminals" },
  { id: "financial-spreading", slug: "financial-spreading", name: "Financial Spreading Agent", description: "Normalize financial information into consistent analytical structures, enabling comparability across borrowers, periods and reporting formats.", href: "/services/financial-ai-agents", categories: ["Finance", "Credit"], mark: "spreading", tone: 2, operation: "Normalize heterogeneous financial inputs", mechanism: "Uneven measures transform against a common datum", metaphor: "Irregular sources resolving into parallel architecture" },
  { id: "credit-memo", slug: "credit-memo", name: "Credit Memo Agent", description: "Synthesize financial, qualitative and risk evidence into a structured credit memo designed to support transparent and consistent credit decisions.", href: "/services/credit-risk", categories: ["Credit"], mark: "synthesis", tone: 5, operation: "Create one defensible analytical synthesis", mechanism: "Independent evidence streams converge and reconcile", metaphor: "Evidence constellation compressed into an authoritative core" },
  { id: "credit-vintage-analysis", slug: "credit-vintage-analysis", name: "Credit Vintage Analysis Agent", description: "Track portfolio performance by origination cohort to reveal behavioural trends, deterioration patterns, roll rates and emerging credit-risk signals.", href: "/resources/credit-vintage-analysis", categories: ["Credit", "Risk & Compliance"], mark: "vintage", tone: 8, operation: "Compare cohorts across common performance horizons", mechanism: "Staggered origins develop through repeated observation points", metaphor: "Temporal cohort landscape with one divergent vintage" },
  { id: "portfolio-monitoring", slug: "portfolio-monitoring", name: "Portfolio Monitoring Agent", description: "Monitor portfolio performance across key dimensions to identify emerging trends, concentrations and anomalies requiring management attention.", href: "/services/credit-risk", categories: ["Credit", "Risk & Compliance"], mark: "portfolio", tone: 3, operation: "Evaluate many signals relative to expected structure", mechanism: "Distributed observations orbit a monitored reference envelope", metaphor: "Signal constellation with one boundary-breaking anomaly" },
  { id: "pd-model-monitoring", slug: "pd-model-monitoring", name: "PD Model Monitoring Agent", description: "Evaluate probability-of-default model performance against observed outcomes, supporting calibration, stability monitoring and early detection of model drift.", href: "/resources/pd-model-monitoring", categories: ["Credit", "Risk & Compliance"], mark: "probability", tone: 6, operation: "Compare expected and observed probability behaviour", mechanism: "Probability fields overlap over time and expose drift", metaphor: "Expected and observed distributions separating at one region" },
  { id: "ifrs-9-ecl-analysis", slug: "ifrs-9-ecl-analysis", name: "IFRS 9 / ECL Analysis Agent", description: "Analyse exposures across IFRS 9 stages, deterioration signals and expected-credit-loss drivers to support consistent impairment analysis and monitoring.", href: "/resources/ifrs-9-expected-credit-loss-architecture", categories: ["Finance", "Credit", "Risk & Compliance"], mark: "riskChambers", tone: 1, operation: "Evaluate deterioration through ordered risk states", mechanism: "Exposure transitions while loss horizons intensify", metaphor: "Three risk chambers crossed by one migrating exposure" },
  { id: "p-and-l-variance", slug: "p-and-l-variance", name: "P&L Variance Agent", description: "Compare actual financial performance with plan or forecast, quantify material variances and surface the drivers requiring management attention.", href: "/services/management-reporting", categories: ["Finance"], mark: "variance", tone: 7, operation: "Evaluate actual performance against budget", mechanism: "Nearly aligned structures create a bounded displacement field", metaphor: "Reference and actual traces separating at material variance" },
  { id: "data-integrity-check", slug: "data-integrity-check", name: "Data Integrity Check Agent", description: "Validate the consistency, completeness and reconciliation of critical data across systems before it enters financial, risk or decision workflows.", href: "/services/risk-ai-agents", categories: ["Finance", "Credit", "Risk & Compliance"], mark: "integrity", tone: 4, operation: "Check data for completeness, consistency, and validity", mechanism: "Controlled checks surface exceptions that require resolution", metaphor: "Data passing through a structured integrity boundary" },
] as const;
