import assert from "node:assert/strict";
import test from "node:test";
import * as XLSX from "xlsx";
import { extract,mapLabel } from "../../backend/financial-intelligence/extraction";
import { evaluateReadiness,summarizeValidation,validate } from "../../backend/financial-intelligence/validation";
import type { InspectedDocument } from "../../backend/lib/files";
import type { CanonicalValue,Evidence } from "../../backend/financial-intelligence/schema";
import { createFinancialIntelligenceHandler } from "../../backend/api/financial-intelligence/http";
import { AgentError } from "../../backend/lib/errors";
import { proposeAmbiguousMappings } from "../../backend/financial-intelligence/model-mapping";

function workbook(rows:unknown[][],name="Income Statement",extension:".xlsx"|".xlsm"=".xlsx"):InspectedDocument{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),name);const buffer=XLSX.write(wb,{type:"buffer",bookType:extension===".xlsm"?"xlsm":"xlsx"});return{fileName:`fixture${extension}`,extension,mimeType:"application/octet-stream",size:buffer.length,buffer}}
test("deterministically extracts comparative cells with evidence and sign normalization",async()=>{const result=await extract(workbook([["Income Statement","2025","2024"],["Currency: EUR; in thousands"],["Revenue",1000,900],["Cost of sales","(400)",-350],["Gross profit",600,550]]));assert.equal(result.values.length,6);assert.equal(result.currency,"EUR");assert.equal(result.scale,1000);assert.equal(result.values.find(v=>v.concept==="cost_of_sales")?.normalizedValue,400);assert.ok(result.values.every(v=>result.evidence.some(e=>e.id===v.evidenceId)));assert.match(result.evidence[0].cellAddress??"",/^[A-Z]+\d+$/)});
test("mixed workbook selects the Income Statement sheet",async()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["Assets",5]]),"Balance Sheet");XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["","2025"],["Revenue",10],["Gross profit",8],["Net income",4]]),"Statement of Operations");const buffer=XLSX.write(wb,{type:"buffer",bookType:"xlsx"});const result=await extract({fileName:"mixed.xlsx",extension:".xlsx",mimeType:"application/octet-stream",size:buffer.length,buffer});assert.equal(result.selected,"Statement of Operations");assert.ok(result.inventory.includes("Balance Sheet"))});
test("rounding tolerance passes but material gross-profit difference fails deterministically",()=>{const evidence:Evidence[]=["r","c","g"].map((x,i)=>({id:x,sourceFilename:"x",kind:"csv",rawRowLabel:x,rawColumnHeader:"2025",rawCellValue:i,structuralContext:"test",extractionMethod:"test"}));const base=(concept:CanonicalValue["concept"],value:number,id:string):CanonicalValue=>({id,sourceRowId:`row-${id}`,sourceLabel:id,normalizedLabel:id,concept,lineType:"component",originalValue:value,normalizedValue:value,sourceSign:"positive",canonicalSign:"positive",normalizationRule:"retained",periodId:"p",currency:"EUR",unitScale:1,mappingMethod:"deterministic",mappingConfidence:1,mappingExplanation:"test",reviewState:"not_required",evidenceId:id});const values=[base("revenue",100,"r"),base("cost_of_sales",40,"c"),base("gross_profit",59.5,"g")];assert.equal(validate(values,evidence).find(c=>c.id.startsWith("gross-profit"))?.status,"passed");values[2].normalizedValue=50;assert.equal(validate(values,evidence).find(c=>c.id.startsWith("gross-profit"))?.status,"failed")});
test("duplicate mappings and missing evidence cannot pass",()=>{const value={id:"a",sourceLabel:"Sales",concept:"revenue",lineType:"component",originalValue:1,normalizedValue:1,sourceSign:"positive",canonicalSign:"positive",normalizationRule:"retained",periodId:"p",currency:null,unitScale:null,mappingMethod:"deterministic",mappingConfidence:1,mappingExplanation:"test",reviewState:"not_required",evidenceId:"missing"} as CanonicalValue;const controls=validate([value,{...value,id:"b",concept:"other_reported_line"}],[]);assert.equal(controls.find(c=>c.id==="duplicate-mapping")?.status,"failed");assert.equal(controls.find(c=>c.id==="evidence-completeness")?.status,"failed")});
test("authorization occurs before multipart parsing",async()=>{let limited=false;const handler=createFinancialIntelligenceHandler({authorize:async()=>{throw new AgentError("AUTHENTICATION_REQUIRED",401)},rateLimiter:{consume:async()=>{limited=true}}});const response=await handler(new Request("http://test",{method:"POST",body:"not multipart"}));assert.equal(response.status,401);assert.equal(limited,false)});
test("XLSM is read as data and formulas are only reported as evidence",async()=>{const result=await extract(workbook([["","2025"],["Revenue",100],["Cost of sales",40],["Gross profit",{f:"B2-B3",v:60}]],"Income Statement",".xlsm"));assert.equal(result.values.length,3);assert.equal(result.evidence.find(e=>e.rawRowLabel==="Gross profit")?.formulaPresent,true)});

const monthlyRows:unknown[][]=[
 ["Example Company"],["Income Statement"],["[USD $ millions]"],
 ["", "Jan 2025","Feb 2025","Mar 2025","YTD Mar 2025","Variance","Margin %"],
 ["Revenue Stream 1",60,70,80,210,5,.1],["Revenue Stream 2",50,55,60,165,2,.1],
 ["Returns, Refunds, Discounts",10,5,10,25,0,.02],["Total Net Revenue",100,120,130,350,7,.2],
 ["Cost of Goods Sold",40,50,55,145,3,.1],["Gross Profit",60,70,75,205,4,.1],
 ["Advertising & Promotion",5,5,5,15,0,.01],["Depreciation & Amortization",2,2,2,6,0,.01],
 ["Insurance",1,1,1,3,0,.01],["Maintenance",1,1,1,3,0,.01],["Office Supplies",1,1,1,3,0,.01],["Rent",2,2,2,6,0,.01],
 ["Net Earnings",48,58,63,169,1,.1]
];
test("monthly structural extraction separates metadata, periods, totals and mappings",async()=>{const result=await extract(workbook(monthlyRows));assert.equal(result.currency,"USD");assert.equal(result.scale,1_000_000);assert.equal(result.rows.find(r=>r.label==="[USD $ millions]")?.role,"metadata");assert.equal(result.values.some(v=>v.sourceLabel.includes("USD")),false);assert.deepEqual(result.periods.map(p=>p.label),["Jan 2025","Feb 2025","Mar 2025","YTD Mar 2025","Variance","Margin %"]);assert.deepEqual(result.periods.map(p=>p.type),["month","month","month","ytd","variance","percentage"]);assert.equal(result.values.some(v=>v.periodId===result.periods[4].id),false);assert.equal(result.values.some(v=>v.periodId===result.periods[5].id),false);assert.equal(result.values.find(v=>v.sourceLabel==="Total Net Revenue")?.concept,"revenue");assert.equal(result.values.find(v=>v.sourceLabel==="Net Earnings")?.concept,"net_income");assert.equal(result.values.find(v=>v.sourceLabel==="Advertising & Promotion")?.concept,"selling_and_distribution_expense");assert.equal(result.values.find(v=>v.sourceLabel==="Insurance")?.concept,"other_operating_expense");assert.ok(result.values.filter(v=>v.sourceLabel.startsWith("Revenue Stream")).every(v=>v.concept==="revenue_component"))});
test("canonical English synonym mapping covers required anchors and operating expenses",()=>{assert.equal(mapLabel("Total Net Revenue").concept,"revenue");assert.equal(mapLabel("Cost of Goods Sold").concept,"cost_of_sales");assert.equal(mapLabel("Gross Margin").concept,"gross_profit");assert.equal(mapLabel("Net Earnings").concept,"net_income");for(const label of ["Advertising & Promotion","G&A","R&D","Insurance","Maintenance","Office Supplies","Rent"])assert.notEqual(mapLabel(label).concept,"other_reported_line")});
test("controls run only when inputs exist and exclude not-applicable from pass counts",async()=>{const result=await extract(workbook(monthlyRows));const controls=validate(result.values,result.evidence,result.scale);assert.equal(controls.some(c=>c.status==="not_applicable"),false);assert.equal(controls.filter(c=>c.id.startsWith("revenue-bridge")).length,4);assert.equal(controls.filter(c=>c.id.startsWith("gross-profit")).length,4);assert.ok(controls.filter(c=>c.id.startsWith("revenue-bridge")||c.id.startsWith("gross-profit")).every(c=>c.status==="passed"));const artificial=[...controls,{...controls[0],id:"na",status:"not_applicable" as const}];const summary=summarizeValidation(artificial,4);assert.equal(summary.passed,controls.filter(c=>c.status==="passed").length);assert.equal(summary.notApplicable,1)});
test("truthful readiness cannot validate low confidence, open tasks, missing anchors, or failed controls",async()=>{const result=await extract(workbook(monthlyRows));const controls=validate(result.values,result.evidence,result.scale);const base={selected:true,statementConfidence:1,periods:result.periods.filter(p=>p.type!=="variance"&&p.type!=="percentage"),values:result.values,evidence:result.evidence,currency:result.currency,unitScale:result.scale,controls,tasks:[]};assert.notEqual(evaluateReadiness({...base,periods:base.periods.map(p=>({...p,confidence:.5,reviewRequired:true}))}).status,"validated");assert.notEqual(evaluateReadiness({...base,tasks:[{id:"x",groupKey:"x",issueType:"low_confidence_mapping",valueId:null,sourceRowId:null,sourceLabel:"x",sourceValue:null,proposedConcept:null,confidence:.58,evidenceId:null,controlIds:[],recommendedAction:"x",material:true,state:"open"}]}).status,"validated");assert.notEqual(evaluateReadiness({...base,values:base.values.map(v=>v.concept==="net_income"?{...v,concept:"other_reported_line" as const}:v)}).status,"validated");assert.notEqual(evaluateReadiness({...base,controls:controls.map((c,i)=>i?c:{...c,status:"failed",material:true})}).status,"validated");const fake=Array.from({length:41},(_,i)=>({...controls[0],id:String(i),status:i<2?"passed" as const:"not_applicable" as const}));const summary=summarizeValidation(fake,18);assert.ok(summary.coverage<.1);assert.ok(summary.passRate<=1)});
test("ambiguous mappings are grouped by source row rather than period value",async()=>{const result=await extract(workbook([...monthlyRows,["Unusual restructuring charge",1,2,3,6]]));const ambiguous=result.values.filter(v=>v.sourceLabel==="Unusual restructuring charge");assert.equal(ambiguous.length,4);assert.equal(new Set(ambiguous.map(v=>v.sourceRowId)).size,1)});
test("model-assisted fallback is label-only, allowlisted, and fails without altering extraction",async()=>{let received:unknown;const valid=await proposeAmbiguousMappings(["Unusual charge"],async labels=>{received=labels;return[{label:"Unusual charge",concept:"other_operating_expense",confidence:.7,explanation:"Operating context",ambiguous:true}]});assert.deepEqual(received,["Unusual charge"]);assert.equal(valid.proposals[0].concept,"other_operating_expense");const invalid=await proposeAmbiguousMappings(["Unusual charge"],async()=>[{label:"Unusual charge",concept:"invented",confidence:2,explanation:"x",ambiguous:false,values:[999]}]);assert.equal(invalid.failed,true);assert.deepEqual(invalid.proposals,[]);const unavailable=await proposeAmbiguousMappings(["Unusual charge"]);assert.equal(unavailable.failed,true)});
