import assert from "node:assert/strict";
import test from "node:test";
import * as XLSX from "xlsx";
import { extract } from "../../backend/financial-intelligence/extraction";
import { validate } from "../../backend/financial-intelligence/validation";
import type { InspectedDocument } from "../../backend/lib/files";
import type { CanonicalValue,Evidence } from "../../backend/financial-intelligence/schema";
import { createFinancialIntelligenceHandler } from "../../backend/api/financial-intelligence/http";
import { AgentError } from "../../backend/lib/errors";

function workbook(rows:unknown[][],name="Income Statement",extension:".xlsx"|".xlsm"=".xlsx"):InspectedDocument{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),name);const buffer=XLSX.write(wb,{type:"buffer",bookType:extension===".xlsm"?"xlsm":"xlsx"});return{fileName:`fixture${extension}`,extension,mimeType:"application/octet-stream",size:buffer.length,buffer}}
test("deterministically extracts comparative cells with evidence and sign normalization",async()=>{const result=await extract(workbook([["Income Statement","2025","2024"],["Currency: EUR; in thousands"],["Revenue",1000,900],["Cost of sales","(400)",-350],["Gross profit",600,550]]));assert.equal(result.values.length,6);assert.equal(result.currency,"EUR");assert.equal(result.scale,1000);assert.equal(result.values.find(v=>v.concept==="cost_of_sales")?.normalizedValue,400);assert.ok(result.values.every(v=>result.evidence.some(e=>e.id===v.evidenceId)));assert.match(result.evidence[0].cellAddress??"",/^[A-Z]+\d+$/)});
test("mixed workbook selects the Income Statement sheet",async()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["Assets",5]]),"Balance Sheet");XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["","2025"],["Revenue",10],["Gross profit",8],["Net income",4]]),"Statement of Operations");const buffer=XLSX.write(wb,{type:"buffer",bookType:"xlsx"});const result=await extract({fileName:"mixed.xlsx",extension:".xlsx",mimeType:"application/octet-stream",size:buffer.length,buffer});assert.equal(result.selected,"Statement of Operations");assert.ok(result.inventory.includes("Balance Sheet"))});
test("rounding tolerance passes but material gross-profit difference fails deterministically",()=>{const evidence:Evidence[]=["r","c","g"].map((x,i)=>({id:x,sourceFilename:"x",kind:"csv",rawRowLabel:x,rawColumnHeader:"2025",rawCellValue:i,structuralContext:"test",extractionMethod:"test"}));const base=(concept:CanonicalValue["concept"],value:number,id:string):CanonicalValue=>({id,sourceLabel:id,concept,lineType:"component",originalValue:value,normalizedValue:value,sourceSign:"positive",canonicalSign:"positive",normalizationRule:"retained",periodId:"p",currency:"EUR",unitScale:1,mappingMethod:"deterministic",mappingConfidence:1,reviewState:"not_required",evidenceId:id});const values=[base("revenue",100,"r"),base("cost_of_sales",40,"c"),base("gross_profit",59.5,"g")];assert.equal(validate(values,evidence).find(c=>c.id.startsWith("gross-profit"))?.status,"passed");values[2].normalizedValue=50;assert.equal(validate(values,evidence).find(c=>c.id.startsWith("gross-profit"))?.status,"failed")});
test("duplicate mappings and missing evidence cannot pass",()=>{const value={id:"a",sourceLabel:"Sales",concept:"revenue",lineType:"component",originalValue:1,normalizedValue:1,sourceSign:"positive",canonicalSign:"positive",normalizationRule:"retained",periodId:"p",currency:null,unitScale:null,mappingMethod:"deterministic",mappingConfidence:1,reviewState:"not_required",evidenceId:"missing"} as CanonicalValue;const controls=validate([value,{...value,id:"b",concept:"other_reported_line"}],[]);assert.equal(controls.find(c=>c.id==="duplicate-mapping")?.status,"failed");assert.equal(controls.find(c=>c.id==="evidence-completeness")?.status,"failed")});
test("authorization occurs before multipart parsing",async()=>{let limited=false;const handler=createFinancialIntelligenceHandler({authorize:async()=>{throw new AgentError("AUTHENTICATION_REQUIRED",401)},rateLimiter:{consume:async()=>{limited=true}}});const response=await handler(new Request("http://test",{method:"POST",body:"not multipart"}));assert.equal(response.status,401);assert.equal(limited,false)});
test("XLSM is read as data and formulas are only reported as evidence",async()=>{const result=await extract(workbook([["","2025"],["Revenue",100],["Cost of sales",40],["Gross profit",{f:"B2-B3",v:60}]],"Income Statement",".xlsm"));assert.equal(result.values.length,3);assert.equal(result.evidence.find(e=>e.rawRowLabel==="Gross profit")?.formulaPresent,true)});
