import assert from "node:assert/strict";import test from "node:test";
import type { FinancialRunRepository,PersistEvent,RunListItem } from "../../backend/financial-intelligence/persistence/contracts";
import { PersistenceConflictError } from "../../backend/financial-intelligence/persistence/contracts";
import { FinancialRunService } from "../../backend/financial-intelligence/persistence/service";
import { runFinancialIntelligence } from "../../backend/financial-intelligence/run";
import { hasValidIntegrity,withFinancialRunIntegrity } from "../../backend/financial-intelligence/run";
import type { FinancialRun } from "../../backend/financial-intelligence/schema";
import * as XLSX from "xlsx";
class DurableFake implements FinancialRunRepository{rows=new Map<string,{owner:string;run:FinancialRun;events:PersistEvent[]}>();async create(owner:string,run:FinancialRun,event:PersistEvent){this.rows.set(run.runId,{owner,run:structuredClone(run),events:[event]});return structuredClone(run)}async list(owner:string){return [...this.rows.values()].filter(x=>x.owner===owner).map(({run}):RunListItem=>({runId:run.runId,filename:run.source.filename,selectedStatement:run.source.selectedSection,status:run.status,periods:run.metrics.periods,financialRows:run.metrics.financialSourceRows,openTasks:run.metrics.reviewTasks,createdAt:run.createdAt!,updatedAt:run.updatedAt!,revision:run.revision!}))}async get(owner:string,id:string){const x=this.rows.get(id);return x?.owner===owner?structuredClone(x.run):null}async update(owner:string,run:FinancialRun,expected:number,event:PersistEvent){const x=this.rows.get(run.runId);if(!x||x.owner!==owner||x.run.revision!==expected)throw new PersistenceConflictError();x.run=structuredClone(run);x.events.push(event);return structuredClone(run)}}
async function fixture(){const ws=XLSX.utils.aoa_to_sheet([["Income Statement","2025"],["Currency: USD; units"],["Revenue",100],["Cost of Sales",40],["Gross Profit",60],["Net Income",20]]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Income Statement");const buffer=XLSX.write(wb,{type:"buffer",bookType:"xlsx"});return runFinancialIntelligence({fileName:"same.xlsx",extension:".xlsx",mimeType:"application/octet-stream",size:buffer.length,buffer})}
test("durable service scopes lists and reads by authenticated owner",async()=>{const repo=new DurableFake(),service=new FinancialRunService(repo),a=await service.create("a",await fixture(),{size:12,fingerprint:"abc"}),b=await service.create("b",await fixture(),{size:12,fingerprint:"def"});assert.deepEqual((await service.list("a")).map(x=>x.runId),[a.runId]);assert.equal(await service.get("a",b.runId),null);assert.equal((await service.get("a",a.runId))?.source.documentFingerprint,"abc")});
test("filename collisions create independent server identifiers and uploaded bytes are absent",async()=>{const repo=new DurableFake(),service=new FinancialRunService(repo),a=await service.create("a",await fixture(),{size:12,fingerprint:"a"}),b=await service.create("a",await fixture(),{size:12,fingerprint:"b"});assert.notEqual(a.runId,b.runId);assert.equal(JSON.stringify([...repo.rows.values()]).includes("buffer"),false)});
test("archive is optimistic, auditable, and read-only",async()=>{const repo=new DurableFake(),service=new FinancialRunService(repo),run=await service.create("a",await fixture(),{size:1,fingerprint:"a"});const archived=await service.archive("a",run.runId,1);assert.equal(archived.status,"archived");assert.equal(repo.rows.get(run.runId)?.events.at(-1)?.type,"run_archived");await assert.rejects(()=>service.archive("a",run.runId,1))});
test("foreign-owner mutations are non-disclosing and stale writes conflict",async()=>{const repo=new DurableFake(),service=new FinancialRunService(repo),run=await service.create("a",await fixture(),{size:1,fingerprint:"a"});await assert.rejects(()=>service.archive("b",run.runId,1),/RUN_NOT_FOUND/);await service.archive("a",run.runId,1);await assert.rejects(()=>repo.update("a",{...run,revision:3},1,{type:"bad"}),PersistenceConflictError)});
test("database-managed timestamps and audit projections do not invalidate the financial contract",async()=>{const run=await fixture();run.revision=1;withFinancialRunIntegrity(run);const hydrated={...run,createdAt:"2026-09-03T10:00:00.123456Z",updatedAt:"2026-09-03T10:01:00.654321Z",validatedAt:"2026-09-03T10:01:00.654321Z",auditEvents:[{eventId:"event-1",eventType:"run_created",actor:"Workspace user",timestamp:"2026-09-03T10:00:00.123456Z",revision:1}]};assert.equal(hasValidIntegrity(hydrated),true);assert.equal(hasValidIntegrity({...hydrated,values:hydrated.values.map((v,i)=>i? v:{...v,normalizedValue:v.normalizedValue+1})}),false)});
test("JSONB key reordering does not invalidate the financial contract",async()=>{const run=await fixture();run.revision=1;withFinancialRunIntegrity(run);const reorder=(value:unknown):unknown=>Array.isArray(value)?value.map(reorder):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).reverse().map(([key,item])=>[key,reorder(item)])):value;const hydrated=reorder(run) as FinancialRun;assert.equal(hasValidIntegrity(hydrated),true);assert.equal(hasValidIntegrity({...hydrated,currency:"EUR"}),false)});
