import assert from "node:assert/strict";import test from "node:test";import * as XLSX from "xlsx";
import {observeDocument} from "../../backend/financial-intelligence/interpretation/adapters";
import {rankMappingCandidates} from "../../backend/financial-intelligence/interpretation/ontology";
import {resolveBoundedSemantic} from "../../backend/financial-intelligence/interpretation/semantic-resolver";
import {lookupMappingMemory,type MappingMemory} from "../../backend/financial-intelligence/interpretation/mapping-memory";
import corpus from "./evaluation/corpus.json" with {type:"json"};
const fixture=()=>{const wb=XLSX.utils.book_new(),sheet=XLSX.utils.aoa_to_sheet([["Income Statement","2025","Variance"],["Revenue",100,4],["  Administrative expenses",20,1]]);sheet.B3={...sheet.B3,f:"B2*0.2"};XLSX.utils.book_append_sheet(wb,sheet,"Statement");const buffer=XLSX.write(wb,{type:"buffer",bookType:"xlsx"});return{fileName:"unseen.xlsx",extension:".xlsx" as const,mimeType:"application/octet-stream",size:buffer.length,buffer}}
test("adapter emits neutral coordinates, formulas, indentation and evidence hashes",async()=>{const observed=await observeDocument(fixture());assert.equal(observed.contractVersion,"observed-document.v1");assert.equal(observed.regions.length,1);assert.ok(observed.regions[0].cells.every(c=>c.row>0&&c.column>0&&c.evidenceHash.length===64));assert.equal(observed.regions[0].cells.find(c=>c.row===3&&c.column===2)?.formula,"B2*0.2")});
test("IFRS and US GAAP ontology variants are contextual and ambiguous labels stay unresolved",()=>{for(const label of ["Personnel costs","Administrative expenses","Income before income taxes","Net profit for the year"])assert.ok(rankMappingCandidates({label,role:"financial_line"}).candidates.length,label);assert.equal(rankMappingCandidates({label:"Exceptional item",role:"financial_line"}).selected,null);const contradiction=rankMappingCandidates({label:"Total operating expenses",role:"note"});assert.equal(contradiction.band,"contradictory");assert.equal(contradiction.selected,null);const equation=rankMappingCandidates({label:"Gross result",role:"subtotal",equationSupport:{gross_profit:1}});assert.equal(equation.candidates[0].concept,"gross_profit")});
test("bounded resolver rejects invented output and degrades to unresolved",async()=>{const request={statementType:"income_statement" as const,sourceLabel:"Exceptional item",normalizedLabel:"exceptional item",rowRole:"financial_line" as const,neighbourLabels:[],hierarchy:[],candidateConcepts:["other_operating_expense" as const],signPattern:"negative" as const,relationshipConstraints:[],currency:null,scale:null};assert.equal((await resolveBoundedSemantic(request)).fallbackReason,"provider_unavailable");assert.equal((await resolveBoundedSemantic(request,async()=>({concept:"invented",confidence:1}))).fallbackReason,"invalid_output")});
test("mapping memory is owner scoped and conflicts never auto-map",()=>{const base={normalizedLabel:"service costs",role:"financial_line" as const,statementType:"income_statement" as const,schemaVersion:"v2"},records:MappingMemory[]=[{...base,id:"1",ownerId:"a",concept:"cost_of_services",active:true,approvedAt:"now"},{...base,id:"2",ownerId:"b",concept:"other_operating_expense",active:true,approvedAt:"now"}];assert.equal(lookupMappingMemory(records,{...base,ownerId:"a"}).concept,"cost_of_services");assert.equal(lookupMappingMemory(records,{...base,ownerId:"c"}).concept,null);records.push({...records[0],id:"3",concept:"other_operating_expense"});assert.equal(lookupMappingMemory(records,{...base,ownerId:"a"}).conflict,true)});
test("sanitized Rieter regression annotation remains two-period, million-scale and currency-honest",()=>{const rieter=corpus.find(x=>x.id==="holdout-ifrs-annual-sanitized")!;assert.equal(rieter.expected.periods,2);assert.equal(rieter.expected.financialRows,30);assert.equal(rieter.expected.values,60);assert.equal(rieter.expected.scale,1_000_000);assert.equal(rieter.expected.currency,null);assert.equal(rieter.expected.readiness,"review_required")});
