import { createHash } from "node:crypto";
import * as XLSX from "xlsx";
import type { InspectedDocument } from "../lib/files";
import { CANONICAL_CONCEPTS,type CanonicalConcept,type CanonicalValue,type Evidence,type Period,type SourceRow,type RowRole } from "./schema";
import { normalizeValue } from "./validation";

const stable=(...p:unknown[])=>createHash("sha256").update(JSON.stringify(p)).digest("hex").slice(0,16);
export const normalizeLabel=(label:string)=>label.toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").trim();
const rules:Array<[RegExp,CanonicalConcept,string]>=[
  [/^(total )?(net )?(revenue|sales)$/,"revenue","reported revenue subtotal"],
  [/^revenue stream(?: \d+)?$/,"revenue_component","revenue component"],
  [/(sales )?(returns?|refunds?|discounts?)( and (allowances?|refunds?|discounts?))?/,"returns_and_allowances","contra-revenue component"],
  [/^(cost of (goods sold|sales)|cogs)$/,"cost_of_sales","cost of sales synonym"],[/^gross (profit|margin)$/,"gross_profit","gross profit amount"],
  [/^(advertising|promotion|advertising and promotion|selling expense|distribution expense)$/,"selling_and_distribution_expense","selling/distribution expense"],
  [/^(general and administrative( expense)?|g and a)$/,"general_and_administrative_expense","G&A expense"],[/^(research and development( expense)?|r and d)$/,"research_and_development_expense","R&D expense"],
  [/^(depreciation|amortization|depreciation and amortization)$/,"depreciation_and_amortization","D&A expense"],
  [/^(insurance|maintenance|office supplies|rent)$/,"other_operating_expense","ordinary operating expense"],[/^total operating expenses?$/,"total_operating_expense","reported operating expense subtotal"],
  [/^other operating income$/,"other_operating_income","other operating income"],[/^(operating profit|operating income|ebit)$/,"operating_profit","operating profit synonym"],
  [/^(finance income|interest income)$/,"finance_income","finance income synonym"],[/^(finance cost|interest expense)$/,"finance_cost","finance cost synonym"],
  [/^(profit before tax|income before tax|earnings before tax)$/,"profit_before_tax","pre-tax profit synonym"],[/^(tax expense|income tax|income tax expense)$/,"income_tax_expense","income tax synonym"],
  [/^(net income|net profit|net earnings|profit for the (year|period))$/,"net_income","net income synonym"],[/^discontinued operations$/,"discontinued_operations","discontinued operations"]
];
export function mapLabel(label:string){const normalized=normalizeLabel(label);const hit=rules.find(([r])=>r.test(normalized));return hit?{normalized,concept:hit[1],confidence:.99,explanation:hit[2]}:{normalized,concept:"other_reported_line" as const,confidence:.4,explanation:"No deterministic allowlisted synonym matched"}}
const numeric=(raw:unknown):number|null=>{if(typeof raw==="number"&&Number.isFinite(raw))return raw;if(typeof raw!=="string")return null;const s=raw.trim();if(!s||s==="-")return null;const n=Number(s.replace(/[,$£€%\s]/g,"").replace(/^\((.*)\)$/,"-$1"));return Number.isFinite(n)?n:null};
function context(text:string){const currency=/\b(USD|EUR|GBP|CAD|AUD)\b/i.exec(text)?.[1]?.toUpperCase()??(/[€]/.test(text)?"EUR":/[£]/.test(text)?"GBP":null);const scale=/\b(?:in |\$ )?millions?\b/i.test(text)?1_000_000:/\b(?:in )?thousands?|\('000\)/i.test(text)?1_000:/\b(?:in )?units?\b/i.test(text)?1:null;return{currency,scale}}
const months=new Map([["jan","01"],["january","01"],["feb","02"],["february","02"],["mar","03"],["march","03"],["apr","04"],["april","04"],["may","05"],["jun","06"],["june","06"],["jul","07"],["july","07"],["aug","08"],["august","08"],["sep","09"],["sept","09"],["september","09"],["oct","10"],["october","10"],["nov","11"],["november","11"],["dec","12"],["december","12"]]);
function parsePeriod(raw:unknown,column:number,yearHint:number|null):Period|null{const originalHeader=raw instanceof Date?raw.toISOString().slice(0,10):String(raw??"").trim();if(!originalHeader)return null;const lower=originalHeader.toLowerCase();const year=Number(/\b(19|20)\d{2}\b/.exec(lower)?.[0]??yearHint)||null;const monthHit=[...months.keys()].find(k=>new RegExp(`\\b${k}\\b`,`i`).test(lower));const month=monthHit?Number(months.get(monthHit)):null;const q=Number(/\bq([1-4])\b/i.exec(lower)?.[1]??0)||null;const designation:Period["designation"]=/budget/i.test(lower)?"budget":/forecast/i.test(lower)?"forecast":/(prior|comparative|previous)/i.test(lower)?"comparative":"actual";let type:Period["type"]="unknown",duration:null|number=null,endDate:null|string=null,label=originalHeader,confidence=.45;if(/%|percentage|margin %/i.test(lower))type="percentage";else if(/variance|\bvar\b|change/i.test(lower))type="variance";else if(/ytd|year to date/i.test(lower)){type="ytd";duration=month;confidence=.95}else if(/annual total|full year|fy total|year total/i.test(lower)){type="annual_total";duration=12;confidence=.95}else if(q){type="quarter";duration=3;confidence=.98;label=`Q${q}${year?` ${year}`:""}`;endDate=year?`${year}-${String(q*3).padStart(2,"0")}-${["31","30","30","31"][q-1]}`:null}else if(month){type=designation==="budget"?"budget":designation==="forecast"?"forecast":"month";duration=1;confidence=year?.98:.82;label=`${new Date(2000,month-1).toLocaleString("en",{month:"short"})}${year?` ${year}`:""}`;endDate=year?new Date(Date.UTC(year,month,0)).toISOString().slice(0,10):null}else if(year){type="year";duration=12;confidence=.95;label=String(year);endDate=`${year}-12-31`}else if(/total/i.test(lower)){type="annual_total";duration=12;confidence=.75}else return null;return{id:`period-${stable(originalHeader,column)}`,originalHeader,label,type,endDate,year,month,quarter:q,designation,durationMonths:duration,sourceColumn:column,confidence,reviewRequired:confidence<.8}}
function roleFor(row:unknown[],index:number,header:number):RowRole{const label=typeof row[0]==="string"?row[0].trim():"";const joined=row.filter(v=>v!==null&&v!=="").join(" ");if(index===header)return"period_header";if(!joined)return"spacer";if(/^\[?\s*(USD|EUR|GBP|CAD|AUD).*\b(millions?|thousands?|units?)\b.*\]?$/i.test(joined)||/^(currency|units?|scale|prepared|unaudited)\b/i.test(label))return"metadata";if(index<header)return index===0?"title":"subtitle";if(!label)return"unknown";if(!row.slice(1).some(v=>numeric(v)!==null))return /^note\b/i.test(label)?"note":"subtitle";if(/^total\b/i.test(label)||/^(gross profit|operating (profit|income)|net (income|profit|earnings)|profit before tax)/i.test(label))return /^total\b/i.test(label)?"total":"subtotal";return"financial_line"}
function buildValue(document:InspectedDocument,label:string,rowNo:number,raw:string|number,p:Period,e:Evidence,role:RowRole):CanonicalValue{const source=numeric(raw)!;const mapped=mapLabel(label);const normalized=normalizeValue(source,mapped.concept);return{id:`value-${e.id}`,sourceRowId:`row-${rowNo}`,sourceLabel:label,normalizedLabel:mapped.normalized,concept:mapped.concept,lineType:role==="subtotal"||role==="total"?"subtotal":"component",originalValue:raw,normalizedValue:normalized,sourceSign:source<0?"negative":source>0?"positive":"zero",canonicalSign:normalized<0?"negative":normalized>0?"positive":"zero",normalizationRule:normalized===source?"source sign retained":"expense converted to positive magnitude",periodId:p.id,currency:null,unitScale:null,mappingMethod:"deterministic",mappingConfidence:mapped.confidence,mappingExplanation:mapped.explanation,reviewState:mapped.concept==="other_reported_line"?"required":"not_required",evidenceId:e.id,originalProposal:mapped.concept}}
export async function extract(document:InspectedDocument){
 if([".xlsx",".xlsm",".csv"].includes(document.extension)){const wb=XLSX.read(document.buffer,{type:"buffer",cellFormula:true,cellText:true,cellDates:true});const inventory=wb.SheetNames;const scores=inventory.map(name=>({name,score:/income|profit|p\s*&\s*l|statement of operations/i.test(name)?10:0}));for(const name of inventory){const rows=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[name],{header:1,raw:true,defval:null});scores.find(s=>s.name===name)!.score+=rows.flat().filter(v=>typeof v==="string"&&/revenue|gross profit|net income|net earnings|profit before tax/i.test(v)).length}scores.sort((a,b)=>b.score-a.score);const selected=scores[0];if(!selected||selected.score<2)return{inventory,selected:null,periods:[],rows:[],evidence:[],values:[],...context("")};const sheet=wb.Sheets[selected.name],data=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,raw:true,defval:null});const meta=context(data.flat().filter(Boolean).join(" "));let header=-1,best=0;for(let i=0;i<Math.min(data.length,20);i++){const score=data[i].slice(1).filter((v,c)=>parsePeriod(v,c+2,null)).length;if(score>best){best=score;header=i}}if(header<0){header=Math.max(0,data.findIndex(r=>r.slice(1).some(v=>numeric(v)!==null))-1)}const yearHint=Number(data.slice(0,header+1).flat().map(String).join(" ").match(/\b(19|20)\d{2}\b/)?.[0])||null;const periods=data[header].map((v,c)=>c?parsePeriod(v,c+1,yearHint):null).filter((p):p is Period=>Boolean(p));const periodByColumn=new Map(periods.map(p=>[p.sourceColumn,p]));const sourceRows:SourceRow[]=data.map((r,i)=>({rowNumber:i+1,label:typeof r[0]==="string"?r[0].trim():"",normalizedLabel:normalizeLabel(typeof r[0]==="string"?r[0]:""),role:roleFor(r,i,header)}));const evidence:Evidence[]=[],values:CanonicalValue[]=[];for(let ri=header+1;ri<data.length;ri++){const row=data[ri],sr=sourceRows[ri];if(!["financial_line","subtotal","total"].includes(sr.role)||!sr.label)continue;for(let ci=1;ci<row.length;ci++){const p=periodByColumn.get(ci+1),raw=row[ci];if(!p||["variance","percentage","helper"].includes(p.type)||numeric(raw)===null)continue;const address=XLSX.utils.encode_cell({r:ri,c:ci}),cell=sheet[address];const e:Evidence={id:`ev-${stable(document.fileName,selected.name,address,String(raw))}`,sourceFilename:document.fileName,kind:document.extension===".csv"?"csv":"spreadsheet",sheetName:selected.name,cellAddress:address,rowNumber:ri+1,columnNumber:ci+1,rawRowLabel:sr.label,rawColumnHeader:p.originalHeader,rawCellValue:raw as string|number,formulaPresent:Boolean(cell?.f),structuralContext:`${sr.role} on ${selected.name}`,extractionMethod:"deterministic-sheet-cell"};evidence.push(e);const v=buildValue(document,sr.label,ri+1,raw as string|number,p,e,sr.role);v.currency=meta.currency;v.unitScale=meta.scale;values.push(v)}}return{inventory,selected:selected.name,periods,rows:sourceRows,evidence,values,...meta}}
 const {default:pdf}=await import("pdf-parse/lib/pdf-parse.js");const data=await pdf(document.buffer),text=data.text.trim();return{inventory:["PDF document"],selected:null,periods:[],rows:[],evidence:[],values:[],...context(text),imageOnly:!text};
}
export function isCanonicalConcept(value:string):value is CanonicalConcept{return(CANONICAL_CONCEPTS as readonly string[]).includes(value)}
