import { createHash } from "node:crypto";
import * as XLSX from "xlsx";
import type { InspectedDocument } from "../lib/files";
import { CANONICAL_CONCEPTS,type CanonicalConcept,type CanonicalValue,type Evidence,type Period } from "./schema";
import { normalizeValue } from "./validation";

const aliases:Array<[RegExp,CanonicalConcept]>=[[/^(total )?(revenue|sales|turnover|net sales)$/i,"revenue"],[/cost of (sales|goods sold)|^cogs$/i,"cost_of_sales"],[/gross profit/i,"gross_profit"],[/other operating income/i,"other_operating_income"],[/selling|distribution/i,"selling_and_distribution_expense"],[/general.{0,5}administrative|administrative expenses?/i,"general_and_administrative_expense"],[/research|development expense|r&d/i,"research_and_development_expense"],[/depreciation|amortization/i,"depreciation_and_amortization"],[/operating (profit|income)/i,"operating_profit"],[/finance income|interest income/i,"finance_income"],[/finance cost|interest expense/i,"finance_cost"],[/profit before tax|income before tax|earnings before tax/i,"profit_before_tax"],[/income tax|tax expense/i,"income_tax_expense"],[/net (income|profit)|profit for the (year|period)/i,"net_income"],[/discontinued operations/i,"discontinued_operations"],[/other operating expense/i,"other_operating_expense"]];
const conceptFor=(label:string)=>aliases.find(([r])=>r.test(label.trim()))?.[1]??"other_reported_line";
const numeric=(raw:unknown):number|null=>{if(typeof raw==="number"&&Number.isFinite(raw))return raw;if(typeof raw!=="string")return null;const s=raw.trim();if(!s||s==="-")return null;const n=Number(s.replace(/[,$£€\s]/g,"").replace(/^\((.*)\)$/,"-$1"));return Number.isFinite(n)?n:null};
const stable=(...p:unknown[])=>createHash("sha256").update(JSON.stringify(p)).digest("hex").slice(0,16);
function context(text:string){const currency=/\b(USD|EUR|GBP|CAD|AUD)\b/i.exec(text)?.[1]?.toUpperCase()??(/[€]/.test(text)?"EUR":/[£]/.test(text)?"GBP":null);const scale=/\b(in )?millions?\b/i.test(text)?1_000_000:/\b(in )?thousands?|\('000\)/i.test(text)?1_000:/\b(in )?units?\b/i.test(text)?1:null;return{currency,scale}}
const period=(label:string,index:number):Period=>{const year=/\b(19|20)\d{2}\b/.exec(label)?.[0];return{id:`period-${stable(label,index)}`,label,endDate:year?`${year}-12-31`:null,durationMonths:/quarter|three months/i.test(label)?3:/year|12 months|\b(19|20)\d{2}\b/i.test(label)?12:null,type:/quarter|three months/i.test(label)?"quarter":/year|12 months|\b(19|20)\d{2}\b/i.test(label)?"year":"unknown",comparison:index===0?"actual":"comparative"}}
function buildValue(document:InspectedDocument,label:string,raw:string|number,p:Period,e:Evidence):CanonicalValue{const source=numeric(raw)!;const concept=conceptFor(label);const normalized=normalizeValue(source,concept);return{id:`value-${e.id}`,sourceLabel:label,concept,lineType:/profit|income before|net income/i.test(label)?"subtotal":"component",originalValue:raw,normalizedValue:normalized,sourceSign:source<0?"negative":source>0?"positive":"zero",canonicalSign:normalized<0?"negative":normalized>0?"positive":"zero",normalizationRule:normalized===source?"source sign retained":"expense converted to positive magnitude",periodId:p.id,currency:null,unitScale:null,mappingMethod:"deterministic",mappingConfidence:concept==="other_reported_line"?.45:.98,reviewState:concept==="other_reported_line"?"required":"not_required",evidenceId:e.id}}
export async function extract(document:InspectedDocument){
  if([".xlsx",".xlsm",".csv"].includes(document.extension)){
    const wb=XLSX.read(document.buffer,{type:"buffer",cellFormula:true,cellText:true,cellDates:false}); const inventory=wb.SheetNames; const scores=inventory.map(name=>({name,score:/income|profit|p\s*&\s*l|statement of operations/i.test(name)?10:0}));
    for(const name of inventory){const sheet=wb.Sheets[name];const rows=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,raw:true,defval:null});scores.find(s=>s.name===name)!.score+=rows.flat().filter(v=>typeof v==="string"&&/revenue|gross profit|net income|profit before tax/i.test(v)).length}
    scores.sort((a,b)=>b.score-a.score); const selected=scores[0]; if(!selected||selected.score<2)return{inventory,selected:null,periods:[],evidence:[],values:[],...context("")};
    const sheet=wb.Sheets[selected.name], rows=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,raw:true,defval:null}); const text=rows.flat().filter(Boolean).join(" "); const meta=context(text); let header=-1; for(let i=0;i<rows.length;i++)if(rows[i].slice(1).some(v=>typeof v==="string"&&(/\b(19|20)\d{2}\b|year ended|quarter/i.test(v)))){header=i;break} if(header<0)header=rows.findIndex(r=>r.slice(1).some(v=>numeric(v)!==null))-1;
    const headers=(rows[Math.max(0,header)]??[]).slice(1).map((v,i)=>String(v??`Column ${i+2}`)); const periods=headers.map(period); const evidence:Evidence[]=[],values:CanonicalValue[]=[];
    rows.slice(Math.max(0,header+1)).forEach((row,ri)=>{const label=typeof row[0]==="string"?row[0].trim():"";if(!label)return;row.slice(1).forEach((raw,ci)=>{if(numeric(raw)===null||!periods[ci])return;const rowNo=Math.max(0,header+1)+ri+1,colNo=ci+2,address=XLSX.utils.encode_cell({r:rowNo-1,c:colNo-1});const cell=sheet[address];const e:Evidence={id:`ev-${stable(document.fileName,selected.name,address,String(raw))}`,sourceFilename:document.fileName,kind:document.extension===".csv"?"csv":"spreadsheet",sheetName:selected.name,cellAddress:address,rowNumber:rowNo,columnNumber:colNo,rawRowLabel:label,rawColumnHeader:headers[ci],rawCellValue:raw as string|number,formulaPresent:Boolean(cell?.f),structuralContext:`Income Statement row on ${selected.name}`,extractionMethod:"deterministic-sheet-cell"};evidence.push(e);const v=buildValue(document,label,raw as string|number,periods[ci],e);v.currency=meta.currency;v.unitScale=meta.scale;values.push(v)})});return{inventory,selected:selected.name,periods,evidence,values,...meta};
  }
  const {default:pdf}=await import("pdf-parse/lib/pdf-parse.js"); const data=await pdf(document.buffer); const text=data.text.trim(); if(!text)return{inventory:[],selected:null,periods:[],evidence:[],values:[],currency:null,scale:null,imageOnly:true}; const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); const heading=lines.findIndex(l=>/income statement|statement of (operations|profit)|profit and loss/i.test(l)); if(heading<0)return{inventory:["PDF document"],selected:null,periods:[],evidence:[],values:[],...context(text)};
  const area=lines.slice(heading); const header=area.find(l=>/\b(19|20)\d{2}\b/.test(l))??"Unknown period"; const labels=header.match(/\b(?:19|20)\d{2}\b/g)??[header]; const periods=labels.map(period),evidence:Evidence[]=[],values:CanonicalValue[]=[]; const meta=context(text);
  for(const line of area){const matches=[...line.matchAll(/\(?[-+]?[$£€]?[\d,]+(?:\.\d+)?\)?/g)];if(!matches.length)continue;const label=line.slice(0,matches[0].index).trim();if(!label||/^\d/.test(label))continue;matches.slice(-periods.length).forEach((m,i)=>{if(!periods[i]||numeric(m[0])===null)return;const e:Evidence={id:`ev-${stable(document.fileName,line,i)}`,sourceFilename:document.fileName,kind:"pdf",sectionIdentifier:"income-statement",rawRowLabel:label,rawColumnHeader:periods[i].label,rawCellValue:m[0],structuralContext:"Extracted line within detected Income Statement text section",extractionMethod:"deterministic-pdf-text"};evidence.push(e);const v=buildValue(document,label,m[0],periods[i],e);v.currency=meta.currency;v.unitScale=meta.scale;values.push(v)})}
  return{inventory:["PDF document"],selected:"income-statement",periods,evidence,values,...meta};
}
export function isCanonicalConcept(value:string):value is CanonicalConcept{return (CANONICAL_CONCEPTS as readonly string[]).includes(value)}
