import { createHash } from "node:crypto";
import * as XLSX from "xlsx";
import type { InspectedDocument } from "../lib/files";
import { CANONICAL_CONCEPTS,type CanonicalConcept,type CanonicalValue,type Evidence,type Period,type PeriodBoundaryDiagnostics,type SheetClassification,type SourceRow,type RowRole,type StatementCandidate } from "./schema";
import { normalizeValue } from "./validation";

const stable=(...p:unknown[])=>createHash("sha256").update(JSON.stringify(p)).digest("hex").slice(0,16);
export const normalizeLabel=(label:string)=>label.toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").trim();
const rules:Array<[RegExp,CanonicalConcept,string]>=[
  [/^(total )?(net )?(revenue|sales)$/,"revenue","Exact allowlisted revenue subtotal synonym"],
  [/^revenue stream(?: \d+)?$/,"revenue_component","Explicit revenue component label"],
  [/(sales )?(returns?|refunds?|discounts?)( and (allowances?|refunds?|discounts?))?/,"returns_and_allowances","Explicit contra-revenue synonym"],
  [/^(cost of (goods sold|sales)|cogs)$/,"cost_of_sales","Exact cost of sales synonym"],[/^gross (profit|margin)$/,"gross_profit","Exact gross profit synonym"],
  [/^(salar(y|ies)( benefits)?( and wages)?|salaries and wages|payroll|personnel costs?)$/,"personnel_expense","Ordinary payroll and personnel-cost synonym"],
  [/^employee benefits?$/,"employee_benefits_expense","Explicit employee-benefits expense"],
  [/^(advertising( and promotion)?|promotion|advertising and promotions?)$/,"advertising_and_promotion_expense","Explicit advertising and promotion expense"],
  [/^(selling expenses?|distribution expenses?|selling and distribution expenses?)$/,"selling_and_distribution_expense","Explicit selling/distribution expense"],
  [/^(general and administrative( expenses?)?|g and a)$/,"general_and_administrative_expense","Exact G&A expense synonym"],
  [/^(research and development( expenses?)?|r and d)$/,"research_and_development_expense","Exact R&D expense synonym"],
  [/^(depreciation|amortization|depreciation and amortization)$/,"depreciation_and_amortization","Explicit D&A expense"],
  [/^insurance( expense)?$/,"insurance_expense","Explicit insurance expense"],[/^maintenance( expense)?$/,"maintenance_expense","Explicit maintenance expense"],
  [/^office supplies?( expense)?$/,"office_supplies_expense","Explicit office-supplies expense"],[/^rent( expense)?$/,"rent_expense","Explicit rent expense"],
  [/^utilities?( expense)?$/,"utilities_expense","Explicit utilities expense"],
  [/^professional fees?$/,"professional_fees_expense","Explicit professional-fees expense"],[/^travel and entertainment( expense)?$/,"travel_and_entertainment_expense","Explicit travel and entertainment expense"],
  [/^other operating expenses?$/,"other_operating_expense","Explicit residual operating-expense label"],[/^total operating expenses?$/,"total_operating_expense","Reported operating-expense subtotal"],
  [/^other operating income$/,"other_operating_income","Explicit other operating income"],[/^(operating profit|operating income|ebit)$/,"operating_profit","Exact operating profit synonym"],
  [/^(finance income|interest income)$/,"finance_income","Exact finance income synonym"],[/^(finance cost|interest expense)$/,"finance_cost","Exact finance cost synonym"],
  [/^(profit before tax|income before tax|earnings before tax)$/,"profit_before_tax","Exact pre-tax profit synonym"],[/^(tax expense|income tax|income tax expense)$/,"income_tax_expense","Exact income tax synonym"],
  [/^(net income|net profit|net earnings|profit for the (year|period))$/,"net_income","Exact net income synonym"],[/^discontinued operations$/,"discontinued_operations","Explicit discontinued operations"]
];
export function mapLabel(label:string){const normalized=normalizeLabel(label);const hit=rules.find(([r])=>r.test(normalized));return hit?{normalized,concept:hit[1],confidence:.99,explanation:hit[2]}:{normalized,concept:"other_reported_line" as const,confidence:.4,explanation:"No deterministic allowlisted English synonym matched"}}
const numeric=(raw:unknown):number|null=>{if(typeof raw==="number"&&Number.isFinite(raw))return raw;if(typeof raw!=="string")return null;const s=raw.trim();if(!s||s==="-")return null;const n=Number(s.replace(/[,$£€%\s]/g,"").replace(/^\((.*)\)$/, "-$1"));return Number.isFinite(n)?n:null};
function context(text:string){const currency=/\b(USD|EUR|GBP|CAD|AUD)\b/i.exec(text)?.[1]?.toUpperCase()??(/[€]/.test(text)?"EUR":/[£]/.test(text)?"GBP":null);const scale=/\b(?:in |\$ )?millions?\b/i.test(text)?1_000_000:/\b(?:in )?thousands?|\('000\)/i.test(text)?1_000:/\b(?:in )?units?\b/i.test(text)?1:null;return{currency,scale}}
const months=new Map([["jan","01"],["january","01"],["feb","02"],["february","02"],["mar","03"],["march","03"],["apr","04"],["april","04"],["may","05"],["jun","06"],["june","06"],["jul","07"],["july","07"],["aug","08"],["august","08"],["sep","09"],["sept","09"],["september","09"],["oct","10"],["october","10"],["nov","11"],["november","11"],["dec","12"],["december","12"]]);
function parsePeriod(raw:unknown,column:number,yearHint:number|null):Period|null{const originalHeader=raw instanceof Date?raw.toISOString().slice(0,10):String(raw??"").trim();if(!originalHeader)return null;const lower=originalHeader.toLowerCase();const explicitYear=/\b(19|20)\d{2}\b/.exec(lower)?.[0];const year=Number(explicitYear??yearHint)||null;const monthHit=[...months.keys()].find(k=>new RegExp(`\\b${k}\\b`,`i`).test(lower));const month=monthHit?Number(months.get(monthHit)):null;const q=Number(/\bq([1-4])\b/i.exec(lower)?.[1]??0)||null;const designation:Period["designation"]=/budget/i.test(lower)?"budget":/forecast/i.test(lower)?"forecast":/(prior|comparative|previous)/i.test(lower)?"comparative":"actual";let type:Period["type"]="unknown",duration:null|number=null,endDate:null|string=null,label=originalHeader,confidence=.45;if(/%|percentage|margin %/i.test(lower))type="percentage";else if(/variance|\bvar\b|change/i.test(lower))type="variance";else if(/ytd|year to date/i.test(lower)){type="ytd";duration=month;confidence=.95}else if(/^(annual total|full year|fy(?: total)?|year total)$/i.test(originalHeader)){type="annual_total";duration=12;confidence=.98}else if(q){type="quarter";duration=3;confidence=.98;label=`Q${q}${year?` ${year}`:""}`;endDate=year?`${year}-${String(q*3).padStart(2,"0")}-${["31","30","30","31"][q-1]}`:null}else if(month){type=designation==="budget"?"budget":designation==="forecast"?"forecast":"month";duration=1;confidence=year?.98:.82;label=`${new Date(2000,month-1).toLocaleString("en",{month:"short"})}${year?` ${year}`:""}`;endDate=year?new Date(Date.UTC(year,month,0)).toISOString().slice(0,10):null}else if(explicitYear&&/^\s*(19|20)\d{2}\s*$/.test(originalHeader)){type="year";duration=12;confidence=.95;label=String(year);endDate=`${year}-12-31`}else return null;return{id:`period-${stable(originalHeader,column)}`,originalHeader,label,type,endDate,year,month,quarter:q,designation,durationMonths:duration,sourceColumn:column,confidence,reviewRequired:confidence<.8}}
function findHeader(data:unknown[][]){let header=-1,best=0;for(let i=0;i<Math.min(data.length,30);i++){const score=data[i].slice(1).filter((v,c)=>parsePeriod(v,c+2,null)).length;if(score>best){best=score;header=i}}return{header,best}}
function periodBoundary(data:unknown[][],header:number):{periods:Period[];diagnostics:PeriodBoundaryDiagnostics}{const rejected:PeriodBoundaryDiagnostics["rejectedColumns"]=[],accepted:PeriodBoundaryDiagnostics["acceptedColumns"]=[];if(header<0)return{periods:[],diagnostics:{headerRow:null,firstAcceptedColumn:null,lastAcceptedColumn:null,stopReason:"No period header row detected",acceptedColumns:[],rejectedColumns:[]}};const headerRow=data[header];const yearHint=Number(data.slice(0,header+1).flat().map(String).join(" ").match(/\b(19|20)\d{2}\b/)?.[0])||null;const periods:Period[]=[];let started=false,stopped=false,stopReason="End of contiguous recognized header range";for(let ci=1;ci<headerRow.length;ci++){const raw=headerRow[ci],text=String(raw??"").trim(),column=ci+1,p=parsePeriod(raw,column,yearHint);if(stopped){if(text)rejected.push({column,address:XLSX.utils.encode_col(ci),header:text,reason:"Column occurs after the financial period boundary"});continue}if(p&&!(["variance","percentage","helper"] as const).includes(p.type as never)){started=true;periods.push(p);accepted.push({column,address:XLSX.utils.encode_col(ci),header:p.originalHeader,type:p.type});if(p.type==="annual_total"){stopped=true;stopReason="Stopped at reported Full Year/annual total column"}}else if(started){if(text)rejected.push({column,address:XLSX.utils.encode_col(ci),header:text,reason:p?`Excluded ${p.type} helper column`:"Unrecognized auxiliary header"});stopped=true;stopReason=`Stopped before non-period column ${XLSX.utils.encode_col(ci)}`}}
return{periods,diagnostics:{headerRow:header+1,firstAcceptedColumn:periods[0]?.sourceColumn??null,lastAcceptedColumn:periods.at(-1)?.sourceColumn??null,stopReason,acceptedColumns:accepted,rejectedColumns:rejected}}}
function roleFor(row:unknown[],index:number,header:number):RowRole{const label=typeof row[0]==="string"?row[0].trim():"";const joined=row.filter(v=>v!==null&&v!=="").join(" ");if(index===header)return"period_header";if(!joined)return"spacer";if(/^\[?\s*(USD|EUR|GBP|CAD|AUD).*\b(millions?|thousands?|units?)\b.*\]?$/i.test(joined)||/^(currency|units?|scale|prepared|unaudited)\b/i.test(label))return"metadata";if(index<header)return index===0?"title":"subtitle";if(!label)return"unknown";if(!row.slice(1).some(v=>numeric(v)!==null))return /^note\b/i.test(label)?"note":"subtitle";if(/^total\b/i.test(label)||/^(gross profit|operating (profit|income)|net (income|profit|earnings)|profit before tax)/i.test(label))return /^total\b/i.test(label)?"total":"subtotal";return"financial_line"}
function classifySheet(name:string,data:unknown[][]):Omit<StatementCandidate,"id"|"selected">{const joined=data.flat().filter(v=>typeof v==="string").join(" ");const incomeName=/income statement|profit\s*&\s*loss|\bp\s*&\s*l\b|statement of operations/i.test(name);const blankName=/blank|template/i.test(name);const cover=/cover|instruction|read me/i.test(name);const other=/balance sheet|cash flow|changes in equity/i.test(name);const supporting=/schedule|detail|support/i.test(name);const anchors=(joined.match(/revenue|gross profit|net income|net earnings|cost of sales/gi)??[]).length;const {header}=findHeader(data);const {periods}=periodBoundary(data,header);const financialRowCount=header<0?0:data.slice(header+1).filter((r,i)=>["financial_line","subtotal","total"].includes(roleFor(r,i+header+1,header))).length;const populated=periods.length>0&&financialRowCount>0&&data.slice(header+1).some(r=>r.slice(1).some(v=>numeric(v)!==null&&numeric(v)!==0));const classification:SheetClassification=cover?"cover_instructions":incomeName&&(blankName||!populated)?"blank_income_statement_template":incomeName&&populated?"populated_income_statement":other?"other_financial_statement":supporting?"supporting_schedule":"unsupported_unknown";const cadence=/month|mnth/i.test(name)||periods.filter(p=>p.type==="month").length>=6?"monthly":/annual|year/i.test(name)||periods.every(p=>["year","annual_total"].includes(p.type))?"annual":"other";const score=(classification==="populated_income_statement"?100:0)+anchors*3+periods.length+(cadence==="monthly"?5:0);return{sheetName:name,classification,statementType:classification.includes("income_statement")?"income_statement":other?"other":null,cadence,executable:classification==="populated_income_statement",score,reason:classification==="populated_income_statement"?`${financialRowCount} financial rows and ${periods.length} recognized periods`:classification==="blank_income_statement_template"?"Income Statement template has no populated financial values":classification.replaceAll("_"," "),financialRowCount,periodCount:periods.length}}
function buildValue(label:string,rowNo:number,raw:string|number,p:Period,e:Evidence,role:RowRole):CanonicalValue{const source=numeric(raw)!;const mapped=mapLabel(label);const normalized=normalizeValue(source,mapped.concept);return{id:`value-${e.id}`,sourceRowId:`row-${rowNo}`,sourceLabel:label,normalizedLabel:mapped.normalized,concept:mapped.concept,lineType:role==="subtotal"||role==="total"?"subtotal":"component",originalValue:raw,normalizedValue:normalized,sourceSign:source<0?"negative":source>0?"positive":"zero",canonicalSign:normalized<0?"negative":normalized>0?"positive":"zero",normalizationRule:normalized===source?"source sign retained":"expense converted to positive magnitude",periodId:p.id,currency:null,unitScale:null,mappingMethod:"deterministic",mappingConfidence:mapped.confidence,mappingExplanation:mapped.explanation,reviewState:mapped.concept==="other_reported_line"?"required":"not_required",evidenceId:e.id,originalProposal:mapped.concept}}
export async function extract(document:InspectedDocument,requestedSheet?:string|null){
 if([".xlsx",".xlsm",".csv"].includes(document.extension)){const wb=XLSX.read(document.buffer,{type:"buffer",cellFormula:true,cellText:true,cellDates:true});const inventory=wb.SheetNames;const candidates=inventory.map((name,i)=>{const data=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[name],{header:1,raw:true,defval:null});return{id:`sheet-${stable(name,i)}`,selected:false,...classifySheet(name,data)}});const executable=candidates.filter(c=>c.executable).sort((a,b)=>b.score-a.score);const selected=(requestedSheet&&executable.find(c=>c.sheetName===requestedSheet))||executable[0]||null;for(const candidate of candidates)candidate.selected=candidate.sheetName===selected?.sheetName;if(!selected)return{inventory,candidates,selected:null,periods:[],periodBoundary:{headerRow:null,firstAcceptedColumn:null,lastAcceptedColumn:null,stopReason:"No populated Income Statement candidate",acceptedColumns:[],rejectedColumns:[]},rows:[],evidence:[],values:[],...context("")};const sheet=wb.Sheets[selected.sheetName],data=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,raw:true,defval:null});const meta=context(data.flat().filter(Boolean).join(" "));const {header}=findHeader(data);const {periods,diagnostics}=periodBoundary(data,header);const periodByColumn=new Map(periods.map(p=>[p.sourceColumn,p]));const sourceRows:SourceRow[]=data.map((r,i)=>({rowNumber:i+1,label:typeof r[0]==="string"?r[0].trim():"",normalizedLabel:normalizeLabel(typeof r[0]==="string"?r[0]:""),role:roleFor(r,i,header)}));const evidence:Evidence[]=[],values:CanonicalValue[]=[];for(let ri=header+1;ri<data.length;ri++){const row=data[ri],sr=sourceRows[ri];if(!["financial_line","subtotal","total"].includes(sr.role)||!sr.label)continue;for(let ci=1;ci<row.length;ci++){const p=periodByColumn.get(ci+1),raw=row[ci];if(!p||numeric(raw)===null)continue;const address=XLSX.utils.encode_cell({r:ri,c:ci}),cell=sheet[address];const e:Evidence={id:`ev-${stable(document.fileName,selected.sheetName,address,String(raw))}`,sourceFilename:document.fileName,kind:document.extension===".csv"?"csv":"spreadsheet",sheetName:selected.sheetName,cellAddress:address,rowNumber:ri+1,columnNumber:ci+1,rawRowLabel:sr.label,rawColumnHeader:p.originalHeader,rawCellValue:raw as string|number,formulaPresent:Boolean(cell?.f),structuralContext:`${sr.role} on selected candidate ${selected.sheetName}`,extractionMethod:"deterministic-table-boundary-cell"};evidence.push(e);const v=buildValue(sr.label,ri+1,raw as string|number,p,e,sr.role);v.currency=meta.currency;v.unitScale=meta.scale;values.push(v)}}return{inventory,candidates,selected:selected.sheetName,periods,periodBoundary:diagnostics,rows:sourceRows,evidence,values,...meta}}
 const {default:pdf}=await import("pdf-parse/lib/pdf-parse.js");const data=await pdf(document.buffer),text=data.text.trim();return{inventory:["PDF document"],candidates:[] as StatementCandidate[],selected:null,periods:[],periodBoundary:{headerRow:null,firstAcceptedColumn:null,lastAcceptedColumn:null,stopReason:"PDF table boundary unavailable",acceptedColumns:[],rejectedColumns:[]},rows:[],evidence:[],values:[],...context(text),imageOnly:!text};
}
export function isCanonicalConcept(value:string):value is CanonicalConcept{return(CANONICAL_CONCEPTS as readonly string[]).includes(value)}
