import { randomUUID } from "node:crypto";
import type { InspectedDocument } from "../lib/files";
import { runInspectedDocumentClassifier } from "../api/agents/document-classifier/run";
import { extract } from "./extraction";
import { CANONICAL_INCOME_STATEMENT_VERSION,type FinancialRun,type ReviewTask } from "./schema";
import { validate } from "./validation";

export async function runFinancialIntelligence(document:InspectedDocument):Promise<FinancialRun>{
  const classified=await runInspectedDocumentClassifier(document); const extracted=await extract(document); const controls=validate(extracted.values,extracted.evidence); const tasks:ReviewTask[]=[];
  if("imageOnly" in extracted&&extracted.imageOnly)tasks.push({id:"review-image",issueType:"image_only_pdf",valueId:null,sourceLabel:"Image-only PDF",sourceValue:null,proposedConcept:null,confidence:0,evidenceId:null,controlIds:[],recommendedAction:"Provide a text-based PDF or spreadsheet. OCR is not enabled.",material:true,state:"open"});
  if(!extracted.selected)tasks.push({id:"review-statement",issueType:"ambiguous_statement",valueId:null,sourceLabel:"Income Statement section",sourceValue:null,proposedConcept:null,confidence:0,evidenceId:null,controlIds:[],recommendedAction:"Provide a document with a clearly labelled English Income Statement.",material:true,state:"open"});
  for(const v of extracted.values.filter(v=>v.reviewState==="required"))tasks.push({id:`review-${v.id}`,issueType:"low_confidence_mapping",valueId:v.id,sourceLabel:v.sourceLabel,sourceValue:v.originalValue,proposedConcept:v.concept,confidence:v.mappingConfidence,evidenceId:v.evidenceId,controlIds:[],recommendedAction:"Accept, reject, or remap this reported line.",material:false,state:"open"});
  if(extracted.values.length&&extracted.currency===null)tasks.push({id:"review-currency",issueType:"unknown_currency",valueId:null,sourceLabel:"Reporting currency",sourceValue:null,proposedConcept:null,confidence:0,evidenceId:null,controlIds:[],recommendedAction:"Confirm the reporting currency from source evidence.",material:true,state:"open"});
  if(extracted.values.length&&extracted.scale===null)tasks.push({id:"review-scale",issueType:"unknown_scale",valueId:null,sourceLabel:"Unit scale",sourceValue:null,proposedConcept:null,confidence:0,evidenceId:null,controlIds:[],recommendedAction:"Confirm whether values are units, thousands, or millions.",material:true,state:"open"});
  for(const c of controls.filter(c=>c.reviewRequired))tasks.push({id:`review-${c.id}`,issueType:c.id==="duplicate-mapping"?"duplicate_mapping":c.id==="evidence-completeness"?"missing_evidence":"failed_reconciliation",valueId:null,sourceLabel:c.formula,sourceValue:c.reportedValue,proposedConcept:null,confidence:0,evidenceId:c.affectedEvidence[0]??null,controlIds:[c.id],recommendedAction:"Inspect source values and mappings; resolve before validation.",material:true,state:"open"});
  const blocked=Boolean("imageOnly" in extracted&&extracted.imageOnly)||!extracted.selected; const material=tasks.some(t=>t.material&&t.state==="open"); const status=blocked?("imageOnly" in extracted&&extracted.imageOnly?"unsupported":"blocked"):material?"review_required":"validated";
  const passed=controls.filter(c=>c.status==="passed").length, applicable=controls.filter(c=>c.status!=="not_applicable").length;
  return{runId:randomUUID(),schemaVersion:CANONICAL_INCOME_STATEMENT_VERSION,status,sessionScoped:true,classification:classified.response,detectedStatements:[...new Set([classified.response.classification.document_type,...extracted.inventory.filter(x=>/balance|cash|income|profit/i.test(x))])],source:{filename:document.fileName,format:document.extension,selectedSection:extracted.selected,inventory:extracted.inventory},periods:extracted.periods,currency:extracted.currency,unitScale:extracted.scale,values:extracted.values,evidence:extracted.evidence,controls,reviewTasks:tasks,confidence:{statementDetection:extracted.selected?1:0,periodDetection:extracted.periods.every(p=>p.type!=="unknown")?1:.5,currencyDetection:extracted.currency?1:0,scaleDetection:extracted.scale?1:0,sourceValueExtraction:extracted.values.length?.95:0,canonicalMapping:extracted.values.length?extracted.values.reduce((a,v)=>a+v.mappingConfidence,0)/extracted.values.length:0,evidenceCompleteness:extracted.values.every(v=>extracted.evidence.some(e=>e.id===v.evidenceId))?1:0,deterministicReconciliation:applicable?passed/applicable:0},workflow:[{id:"intake",label:"File Intake",state:"completed"},{id:"classification",label:"Document Classification",state:"completed"},{id:"detection",label:"Statement Detection",state:extracted.selected?"completed":"blocked"},{id:"extraction",label:"Income Statement Extraction",state:extracted.values.length?"completed":blocked?"blocked":"warning"},{id:"mapping",label:"Canonical Mapping",state:extracted.values.length?"completed":"skipped"},{id:"validation",label:"Financial Validation",state:controls.some(c=>c.status==="failed")?"warning":extracted.values.length?"completed":"skipped"},{id:"review",label:"Human Review",state:tasks.length?"review_required":"skipped"},{id:"result",label:"Validated Result",state:status==="validated"?"completed":"blocked"}]};
}
