export const CANONICAL_INCOME_STATEMENT_VERSION = "income-statement.v1" as const;

export const CANONICAL_CONCEPTS = ["revenue","cost_of_sales","gross_profit","other_operating_income","selling_and_distribution_expense","general_and_administrative_expense","research_and_development_expense","other_operating_expense","depreciation_and_amortization","operating_profit","finance_income","finance_cost","profit_before_tax","income_tax_expense","net_income","discontinued_operations","other_reported_line"] as const;
export type CanonicalConcept = typeof CANONICAL_CONCEPTS[number];
export type MappingMethod = "deterministic"|"model-assisted"|"human-validated";
export type ReviewState = "not_required"|"required"|"accepted"|"rejected";
export type Period = { id:string; label:string; endDate:string|null; durationMonths:number|null; type:"month"|"quarter"|"year"|"unknown"; comparison:"actual"|"comparative"|"unknown" };
export type Evidence = { id:string; sourceFilename:string; kind:"spreadsheet"|"pdf"|"csv"; sheetName?:string; cellAddress?:string; rowNumber?:number; columnNumber?:number; pageNumber?:number; sectionIdentifier?:string; rawRowLabel:string; rawColumnHeader:string; rawCellValue:string|number; formulaPresent?:boolean; structuralContext:string; extractionMethod:string };
export type CanonicalValue = { id:string; sourceLabel:string; concept:CanonicalConcept; lineType:"subtotal"|"component"; originalValue:string|number; normalizedValue:number; sourceSign:"positive"|"negative"|"zero"; canonicalSign:"positive"|"negative"|"zero"; normalizationRule:string; periodId:string; currency:string|null; unitScale:number|null; mappingMethod:MappingMethod; mappingConfidence:number; reviewState:ReviewState; evidenceId:string; excludedFromControls?:boolean; originalProposal?:CanonicalConcept };
export type Control = { id:string; formula:string; inputs:Array<{concept:CanonicalConcept;value:number;evidenceId:string}>; expectedValue:number|null; reportedValue:number|null; difference:number|null; tolerance:number; status:"passed"|"warning"|"failed"|"not_applicable"; affectedEvidence:string[]; reviewRequired:boolean };
export type ReviewIssue = "ambiguous_statement"|"ambiguous_period"|"unknown_currency"|"unknown_scale"|"low_confidence_mapping"|"failed_reconciliation"|"duplicate_mapping"|"missing_evidence"|"image_only_pdf"|"conflicting_totals"|"model_failure";
export type ReviewTask = { id:string; issueType:ReviewIssue; valueId:string|null; sourceLabel:string; sourceValue:string|number|null; proposedConcept:CanonicalConcept|null; confidence:number; evidenceId:string|null; controlIds:string[]; recommendedAction:string; material:boolean; state:"open"|"resolved" };
export type FinancialRun = { runId:string; schemaVersion:typeof CANONICAL_INCOME_STATEMENT_VERSION; status:"validated"|"review_required"|"blocked"|"unsupported"; sessionScoped:true; classification:unknown; detectedStatements:string[]; source:{filename:string;format:string;selectedSection:string|null;inventory:string[]}; periods:Period[]; currency:string|null; unitScale:number|null; values:CanonicalValue[]; evidence:Evidence[]; controls:Control[]; reviewTasks:ReviewTask[]; confidence:{statementDetection:number;periodDetection:number;currencyDetection:number;scaleDetection:number;sourceValueExtraction:number;canonicalMapping:number;evidenceCompleteness:number;deterministicReconciliation:number}; workflow:Array<{id:string;label:string;state:"completed"|"warning"|"blocked"|"review_required"|"skipped"}> };
