import test from "node:test";
import assert from "node:assert/strict";
import { inspectFileBuffer } from "../../../backend/lib/files";

const env={DOCUMENT_UPLOAD_S3_ENDPOINT:"https://private.example.test/bucket",DOCUMENT_UPLOAD_S3_REGION:"eu-central-1",DOCUMENT_UPLOAD_S3_ACCESS_KEY_ID:"synthetic-key",DOCUMENT_UPLOAD_S3_SECRET_ACCESS_KEY:"synthetic-secret",DOCUMENT_UPLOAD_REFERENCE_SECRET:"synthetic-reference-secret"};
Object.assign(process.env,env);

test("authorized grant is scoped, signed, private-store-only, and neutralizes traversal",async()=>{const {issueUpload,verifyReference}=await import("../../../backend/lib/private-upload");const grant=issueUpload("actor-a",{fileName:"../../board.pdf",mimeType:"application/pdf",size:100});assert.match(grant.upload_url,/^https:\/\/private\.example\.test\/bucket\/classifier-temp\//);assert.doesNotMatch(grant.upload_url,/board\.pdf/);const ref=verifyReference(grant.upload_reference,"actor-a");assert.equal(ref.name,"board.pdf");assert.ok(ref.key.endsWith(".pdf"));});
test("tampered and cross-actor references are rejected",async()=>{const {issueUpload,verifyReference}=await import("../../../backend/lib/private-upload");const grant=issueUpload("actor-a",{fileName:"safe.pdf",mimeType:"application/pdf",size:100});assert.throws(()=>verifyReference(`${grant.upload_reference}x`,"actor-a"),/invalid/i);assert.throws(()=>verifyReference(grant.upload_reference,"actor-b"),/invalid/i);});
test("expired references are rejected",async()=>{const {issueUpload,verifyReference}=await import("../../../backend/lib/private-upload");const grant=issueUpload("actor-a",{fileName:"safe.pdf",mimeType:"application/pdf",size:100});const original=Date.now;Date.now=()=>original()+6*60*1000;try{assert.throws(()=>verifyReference(grant.upload_reference,"actor-a"),/expired/i);}finally{Date.now=original;}});
test("limit and signature validation happen before classification",async()=>{const {issueUpload}=await import("../../../backend/lib/private-upload");assert.throws(()=>issueUpload("actor",{fileName:"large.pdf",mimeType:"application/pdf",size:20*1024*1024+1}),/size/i);assert.throws(()=>inspectFileBuffer("bad.pdf","application/pdf",Buffer.from("not pdf")),/corrupt/i);assert.throws(()=>inspectFileBuffer("bad.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",Buffer.from("not zip")),/corrupt/i);});
test("synthetic 4.7 MiB payload is represented by a bounded reference, not the run body",async()=>{const {issueUpload}=await import("../../../backend/lib/private-upload");const size=Math.ceil(4.7*1024*1024),grant=issueUpload("actor",{fileName:"synthetic.pdf",mimeType:"application/pdf",size});const body=JSON.stringify({upload_reference:grant.upload_reference});assert.ok(Buffer.byteLength(body)<2048);assert.ok(size>4.5*1024*1024&&size<20*1024*1024);});
