import { createHash,randomUUID } from "node:crypto";
import { AgentError,errorResponse } from "../../lib/errors";
import type { ExecutionRateLimiter } from "../../lib/rate-limit";
import type { AuthorizedActor } from "../../../lib/execution-auth";
import { DOCUMENT_CLASSIFIER_MAX_REQUEST_BYTES } from "../../../lib/document-classifier-upload";
import { inspectUploadedFile } from "../../lib/files";
import { runFinancialIntelligence } from "../../financial-intelligence/run";
import type { FinancialRunService } from "../../financial-intelligence/persistence/service";

export function createFinancialIntelligenceHandler(deps:{authorize:()=>Promise<AuthorizedActor>;rateLimiter:ExecutionRateLimiter;service?:FinancialRunService}){return async(request:Request)=>{const runId=randomUUID();try{const actor=await deps.authorize();await deps.rateLimiter.consume(actor.actorId);const length=Number(request.headers.get("content-length"));if(Number.isFinite(length)&&length>DOCUMENT_CLASSIFIER_MAX_REQUEST_BYTES)throw new AgentError("FILE_TOO_LARGE",413);if(!(request.headers.get("content-type")??"").toLowerCase().startsWith("multipart/form-data"))throw new AgentError("FILE_MISSING",400);let form:FormData;try{form=await request.formData()}catch(error){throw new AgentError("FILE_MISSING",400,"Malformed multipart form data.",error)}if([...form.keys()].some(k=>!["file","selectedSheet"].includes(k))||form.getAll("file").length!==1||form.getAll("selectedSheet").length>1)throw new AgentError("FILE_MISSING",400,"Expected exactly one file and an optional selected sheet.");const selectedSheet=form.get("selectedSheet");if(selectedSheet!==null&&(typeof selectedSheet!=="string"||selectedSheet.length>200))throw new AgentError("FILE_CORRUPT",400,"Invalid selected sheet.");const document=await inspectUploadedFile(form.get("file"));let result=await runFinancialIntelligence(document,selectedSheet||null);if(deps.service)result=await deps.service.create(actor.actorId,result,{size:document.size,fingerprint:createHash("sha256").update(document.buffer).digest("hex")});return Response.json(result,{headers:{"Cache-Control":"no-store"}})}catch(error){return errorResponse(error instanceof AgentError?error:new AgentError("INTERNAL_ERROR",500,undefined,error),runId)}}}
