import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import path from "node:path";
import { AgentError } from "./errors";
import { inspectFileBuffer } from "./files";

const allowed = new Map([[".pdf", ["application/pdf"]], [".xlsx", ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/octet-stream"]], [".xlsm", ["application/vnd.ms-excel.sheet.macroenabled.12", "application/octet-stream"]], [".xls", ["application/vnd.ms-excel", "application/octet-stream"]], [".csv", ["text/csv", "application/csv", "text/plain", "application/vnd.ms-excel", "application/octet-stream"]], [".txt", ["text/plain", "application/octet-stream"]], [".docx", ["application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/octet-stream"]]]);
const maxBytes = () => { const n=Number(process.env.DOCUMENT_CLASSIFIER_MAX_FILE_BYTES); return Number.isInteger(n)&&n>0?n:20*1024*1024; };
const ttl = () => 5 * 60;
type Ref = { v:1; actor:string; key:string; name:string; mime:string; size:number; exp:number; uploadId:string };
function config() { const endpoint=process.env.DOCUMENT_UPLOAD_S3_ENDPOINT, region=process.env.DOCUMENT_UPLOAD_S3_REGION, accessKey=process.env.DOCUMENT_UPLOAD_S3_ACCESS_KEY_ID, secret=process.env.DOCUMENT_UPLOAD_S3_SECRET_ACCESS_KEY, signing=process.env.DOCUMENT_UPLOAD_REFERENCE_SECRET || process.env.AUTH_SECRET; if(!endpoint||!region||!accessKey||!secret||!signing) throw new AgentError("STORAGE_UNAVAILABLE",503); const url=new URL(endpoint); if(url.protocol!=="https:"||url.username||url.password||url.search||url.hash) throw new AgentError("STORAGE_UNAVAILABLE",503); return {url,region,accessKey,secret,signing}; }
const hex=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const hmac=(key:string|Buffer,value:string)=>createHmac("sha256",key).update(value).digest();
function awsUrl(method:string,key:string,expires:number) { const c=config(), now=new Date(), stamp=now.toISOString().replace(/[:-]|\.\d{3}/g,""); const day=stamp.slice(0,8), scope=`${day}/${c.region}/s3/aws4_request`, pathname=`${c.url.pathname.replace(/\/$/,"")}/${key.split("/").map(encodeURIComponent).join("/")}`.replace(/\/+/g,"/"); const q=new URLSearchParams({"X-Amz-Algorithm":"AWS4-HMAC-SHA256","X-Amz-Credential":`${c.accessKey}/${scope}`,"X-Amz-Date":stamp,"X-Amz-Expires":String(expires),"X-Amz-SignedHeaders":"host"}); q.sort(); const canonical=[method,pathname,q.toString(),`host:${c.url.host}\n`,"host","UNSIGNED-PAYLOAD"].join("\n"); const toSign=["AWS4-HMAC-SHA256",stamp,scope,hex(canonical)].join("\n"); const signing=hmac(hmac(hmac(hmac(`AWS4${c.secret}`,day),c.region),"s3"),"aws4_request"); q.set("X-Amz-Signature",hmac(signing,toSign).toString("hex")); return `${c.url.origin}${pathname}?${q}`; }
function sign(payload:string) { return createHmac("sha256",config().signing).update(payload).digest("base64url"); }
export function issueUpload(actor:string,input:unknown) { if(!input||typeof input!=="object") throw new AgentError("FILE_MISSING",400); const {fileName,mimeType,size}=input as Record<string,unknown>; if(typeof fileName!=="string"||typeof mimeType!=="string"||typeof size!=="number") throw new AgentError("FILE_MISSING",400); if(size<=0||size>maxBytes()) throw new AgentError("FILE_TOO_LARGE",413); const name=path.basename(fileName).replace(/[^a-zA-Z0-9._-]/g,"_").slice(-120), ext=path.extname(name).toLowerCase(); if(!allowed.get(ext)?.includes(mimeType.toLowerCase()||"application/octet-stream")) throw new AgentError("UNSUPPORTED_FILE_TYPE",415); const uploadId=randomBytes(18).toString("base64url"), key=`classifier-temp/${new Date().toISOString().slice(0,10)}/${uploadId}${ext}`, ref:Ref={v:1,actor,key,name,mime:mimeType.toLowerCase(),size,exp:Math.floor(Date.now()/1000)+ttl(),uploadId}; const payload=Buffer.from(JSON.stringify(ref)).toString("base64url"); return {upload_url:awsUrl("PUT",key,ttl()), upload_reference:`${payload}.${sign(payload)}`, expires_at:new Date(ref.exp*1000).toISOString(), max_file_bytes:maxBytes(), upload_id:uploadId}; }
export function verifyReference(token:string,actor:string):Ref { const parts=token.split("."); if(parts.length!==2) throw new AgentError("UPLOAD_REFERENCE_INVALID",400); const expected=Buffer.from(sign(parts[0]),"base64url"), actual=Buffer.from(parts[1],"base64url"); if(actual.length!==expected.length||!timingSafeEqual(actual,expected)) throw new AgentError("UPLOAD_REFERENCE_INVALID",400); let ref:Ref; try{ref=JSON.parse(Buffer.from(parts[0],"base64url").toString()) as Ref;}catch{throw new AgentError("UPLOAD_REFERENCE_INVALID",400);} if(ref.v!==1||ref.actor!==actor||!ref.key.startsWith("classifier-temp/")||ref.key.includes("..")||ref.size>maxBytes()) throw new AgentError("UPLOAD_REFERENCE_INVALID",400); if(ref.exp<Math.floor(Date.now()/1000)) throw new AgentError("UPLOAD_AUTHORIZATION_EXPIRED",410); return ref; }
export async function downloadUpload(ref:Ref) { const response=await fetch(awsUrl("GET",ref.key,60),{cache:"no-store",signal:AbortSignal.timeout(20_000)}); if(!response.ok) throw new AgentError("UPLOAD_FAILED",422); const length=Number(response.headers.get("content-length")); if(Number.isFinite(length)&&length>maxBytes()) throw new AgentError("FILE_TOO_LARGE",413); const buffer=Buffer.from(await response.arrayBuffer()); return inspectFileBuffer(ref.name,ref.mime,buffer,ref.size); }
export async function deleteUpload(ref:Ref) { const response=await fetch(awsUrl("DELETE",ref.key,60),{method:"DELETE",cache:"no-store",signal:AbortSignal.timeout(10_000)}); if(!response.ok) throw new Error("temporary object deletion failed"); }
