import * as XLSX from "xlsx";
import { z } from "zod";
import { AgentError } from "../../lib/errors";
import type { InspectedDocument } from "../../lib/files";
import { createResponse, getDocumentClassifierModel } from "../../lib/openai";

export const FINANCIAL_SHEET_TYPES = ["income_statement","balance_sheet","cash_flow_statement","trial_balance","general_ledger","chart_of_accounts","budget","forecast","budget_vs_actual","ar_ageing","ap_ageing","fixed_asset_register","inventory_report","sales_report","purchase_report","cost_centre_report","bank_transactions","invoice_register","mapping_reference","account_balance_detail","other_financial_dataset","unsupported_or_unknown"] as const;
export type FinancialSheetType = typeof FINANCIAL_SHEET_TYPES[number];
export type ClassificationCandidate = { type: FinancialSheetType; confidence: number };
export type EvidenceSignal = { kind: "sheet_name"|"header"|"structure"; description: string; weight: number };
export type SheetFingerprint = { sheet_name:string; row_count:number; column_count:number; inspected_cells:number; numeric_density:number; date_density:number; formula_density:number; normalized_headers:string[]; empty:boolean };
export type SheetClassification = { sheet_name:string; canonical_type:FinancialSheetType; display_label:string; detected_language:"bg"|"en"|"mixed"|"unknown"; confidence:number; local_confidence:number; ai_confidence:number|null; final_confidence:number; classification_source:"deterministic"|"ai"|"deterministic_plus_ai"|"human"; candidates:ClassificationCandidate[]; evidence:EvidenceSignal[]; warnings:string[]; recommended_workflow:string; review_required:boolean; included_in_analysis:boolean; fingerprint:SheetFingerprint };
export type WorkbookComposition = { type:"single_purpose_workbook"|"mixed_financial_workbook"|"reference_or_mapping_workbook"|"unsupported_or_unknown_workbook"; display_label:string; sheet_count:number; included_sheets:number; ignored_empty_sheets:number; high_confidence_sheets:number; review_required_sheets:number; detected_languages:string[]; warnings:string[]; recommended_primary_entry_point:string };
export type WorkbookIntakeResult = { workbook_fingerprint:{ file_name:string; format:"xlsx"|"xlsm"; sheet_count:number; inspected_sheet_count:number; has_macros:boolean; has_external_links:boolean; warnings:string[] }; sheets:SheetClassification[]; composition:WorkbookComposition; review_tasks:Array<{ sheet_name:string; reason:string; proposed_type:FinancialSheetType; candidates:ClassificationCandidate[]; actions:Array<"accept"|"change"|"include"|"exclude"|"mark_as_reference">; persistence:"session_only" }> };

const MAX_SHEETS=40, MAX_ROWS=250, MAX_COLUMNS=40, MAX_CELLS=20_000;
const label=(type:FinancialSheetType)=>type.split("_").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ");
export function normalizeFinancialLabel(value:unknown){return String(value??"").normalize("NFKC").toLocaleLowerCase("bg").replace(/[\p{P}\p{S}_]+/gu," ").replace(/\s+/g," ").trim()}
const rules:Record<Exclude<FinancialSheetType,"other_financial_dataset"|"unsupported_or_unknown">,string[][]>={
 income_statement:[["опр","отчет за приходите и разходите","income statement","profit and loss","revenue","cost of sales","gross profit"]],
 balance_sheet:[["баланс","отчет за финансовото състояние","balance sheet"],["assets","liabilities","активи","пасиви"]],
 cash_flow_statement:[["отчет за паричните потоци","cash flow statement","cash flows"]],
 trial_balance:[["оборотна ведомост","trial balance"],["начален дебит","начален кредит","дебитен оборот","кредитен оборот","крайно дебитно салдо","крайно кредитно салдо","opening debit","opening credit","debit turnover","credit turnover","closing debit","closing credit"]],
 general_ledger:[["главна книга","general ledger","gl account","сметка от главна книга"],["debit","credit","дебит","кредит"]],
 chart_of_accounts:[["сметкоплан","chart of accounts"],["account code","account number","номер на сметка","наименование на сметка","account name"]],
 budget:[["бюджет","budget"],["budget amount","budget period"]], forecast:[["прогноза","forecast"],["forecast amount","forecast period"]],
 budget_vs_actual:[["budget vs actual","бюджет спрямо отчет","variance"],["budget","actual","variance","бюджет","факт","отклонение"]],
 ar_ageing:[["вземания","accounts receivable","ar ageing","customer ageing"],["просрочие","overdue","current","30 days","60 days","90 days"]],
 ap_ageing:[["задължения","accounts payable","ap ageing","vendor ageing"],["просрочие","overdue","current","30 days","60 days","90 days"]],
 fixed_asset_register:[["дълготрайни активи","дма","амортизационен план","fixed asset register","asset register"],["asset number","acquisition value","натрупана амортизация","planned depreciation","планирана амортизация","начална отчетна стойност","крайна отчетна стойност"]],
 inventory_report:[["складова наличност","inventory","stock on hand"],["quantity","sku","material"]], sales_report:[["продажби","sales report"],["customer","revenue","quantity"]], purchase_report:[["покупки","purchase report"],["vendor","purchase amount","quantity"]],
 cost_centre_report:[["разходен център","cost centre","cost center"],["company code","фирмен код","cost"]], bank_transactions:[["банкова сметка","bank transactions","bank account"],["value date","transaction date","amount"]],
 invoice_register:[["фактура","invoice register","credit note","кредитно известие"],["invoice date","vendor","amount"]], mapping_reference:[["mapping","reference","съответствие"],["source account","target account"]],
 account_balance_detail:[["account balance","салда по сметки","settlements"],["opening balance","closing balance","начално салдо","крайно салдо"]]
};
function contains(values:string[], term:string){return values.some(v=>v===term||v.includes(term))}
function classify(fp:SheetFingerprint):Omit<SheetClassification,"sheet_name"|"fingerprint">{
 const all=[normalizeFinancialLabel(fp.sheet_name),...fp.normalized_headers]; const scored:ClassificationCandidate[]=[]; const evidenceBy=new Map<FinancialSheetType,EvidenceSignal[]>();
 for(const [type,groups] of Object.entries(rules) as [FinancialSheetType,string[][]][]){let score=0;const ev:EvidenceSignal[]=[];for(const [i,group] of groups.entries()){const hits=group.filter(t=>contains(all,t));if(hits.length){const add=Math.min(i?0.48:0.42, hits.length*(i?0.12:0.30));score+=add;ev.push({kind:i?"header":"sheet_name",description:`Recognized ${hits.slice(0,4).join(", ")}`,weight:Number(add.toFixed(2))})}}if(fp.numeric_density>.15){score+=.08;ev.push({kind:"structure",description:"Tabular numeric structure detected",weight:.08})}if(score>0){scored.push({type,confidence:Math.min(.99,Number(score.toFixed(2)))});evidenceBy.set(type,ev)}}
 scored.sort((a,b)=>b.confidence-a.confidence);const best=scored[0];const ambiguous=Boolean(best&&scored[1]&&best.confidence-scored[1].confidence<.12);const type=best?.confidence>=.28?best.type:(fp.row_count>2&&fp.column_count>1?"other_financial_dataset":"unsupported_or_unknown");const conf=best?.confidence??(type==="other_financial_dataset"?.35:.1);const review=conf<.78||ambiguous;const bg=all.some(v=>/[а-я]/iu.test(v)),en=all.some(v=>/\b(account|asset|amount|budget|invoice|revenue|debit|credit)\b/i.test(v));
 return {canonical_type:type,display_label:label(type),detected_language:bg&&en?"mixed":bg?"bg":en?"en":"unknown",confidence:conf,local_confidence:conf,ai_confidence:null,final_confidence:conf,classification_source:"deterministic",candidates:scored.slice(0,3),evidence:evidenceBy.get(type)??[{kind:"structure",description:"No controlled financial header combination was established",weight:.1}],warnings:review?[ambiguous?"Candidate scores are materially ambiguous.":"Deterministic confidence is below the approval threshold."]:[],recommended_workflow:type==="mapping_reference"?"mapping_review":type==="unsupported_or_unknown"?"intake_review":`${type}_extraction`,review_required:review,included_in_analysis:type!=="mapping_reference"&&type!=="unsupported_or_unknown"};
}
export const AISheetResultSchema=z.object({canonical_type:z.enum(FINANCIAL_SHEET_TYPES),confidence:z.number().min(0).max(1),evidence:z.array(z.string().max(120)).max(4)}).strict();
export type AISheetClassifier=(input:{sheet_name:string;normalized_headers:string[];fingerprint:Omit<SheetFingerprint,"normalized_headers"|"sheet_name">;candidates:ClassificationCandidate[]})=>Promise<z.infer<typeof AISheetResultSchema>>;
const AI_SHEET_SCHEMA={type:"object",additionalProperties:false,required:["canonical_type","confidence","evidence"],properties:{canonical_type:{type:"string",enum:FINANCIAL_SHEET_TYPES},confidence:{type:"number",minimum:0,maximum:1},evidence:{type:"array",maxItems:4,items:{type:"string",maxLength:120}}}} as const;
export const classifyFinancialSheetWithAI:AISheetClassifier=async input=>{const response=await createResponse({model:getDocumentClassifierModel(),store:false,instructions:"Classify this bounded, value-free workbook sheet structure. Do not infer people, entities, or financial values. Return only the schema.",reasoning:{effort:"none"},max_output_tokens:180,input:JSON.stringify(input),text:{format:{type:"json_schema",name:"financial_sheet_classification",strict:true,schema:AI_SHEET_SCHEMA}}});if(response.status!=="completed")throw new AgentError("CLASSIFICATION_FAILED",502);try{return AISheetResultSchema.parse(JSON.parse(response.output_text))}catch(error){throw new AgentError("OPENAI_RESPONSE_INVALID",502,undefined,error)}};
export async function applySelectiveAIFallback(result:WorkbookIntakeResult,ai:AISheetClassifier=classifyFinancialSheetWithAI){let calls=0;for(const sheet of result.sheets.filter(s=>s.review_required)){try{calls++;const {sheet_name,normalized_headers,...safeFingerprint}=sheet.fingerprint;const answer=await ai({sheet_name,normalized_headers,fingerprint:safeFingerprint,candidates:sheet.candidates});sheet.ai_confidence=answer.confidence;sheet.classification_source=answer.canonical_type===sheet.canonical_type?"deterministic_plus_ai":"ai";sheet.canonical_type=answer.canonical_type;sheet.display_label=label(answer.canonical_type);sheet.final_confidence=answer.confidence;sheet.confidence=answer.confidence;sheet.evidence.push(...answer.evidence.map(description=>({kind:"structure" as const,description,weight:0})));sheet.review_required=answer.confidence<.8;sheet.warnings=sheet.review_required?["AI confidence remains below the approval threshold."]:[]}catch{sheet.warnings.push("AI fallback was unavailable; targeted review is required.");sheet.review_required=true}}result.composition.review_required_sheets=result.sheets.filter(s=>s.review_required).length;result.composition.high_confidence_sheets=result.sheets.filter(s=>!s.review_required).length;result.review_tasks=result.sheets.filter(s=>s.review_required).map(s=>({sheet_name:s.sheet_name,reason:s.warnings[0]??"Classification confirmation required.",proposed_type:s.canonical_type,candidates:s.candidates,actions:["accept","change","include","exclude","mark_as_reference"],persistence:"session_only"}));return calls}
export function parseFinancialWorkbook(document:InspectedDocument):WorkbookIntakeResult{
 if(document.extension!==".xlsx"&&document.extension!==".xlsm")throw new AgentError("UNSUPPORTED_FILE_TYPE",415);
 const wb=XLSX.read(document.buffer,{type:"buffer",cellDates:true,cellFormula:false,cellHTML:false,bookVBA:false,bookFiles:false,sheetRows:MAX_ROWS});if(wb.SheetNames.length>MAX_SHEETS)throw new AgentError("WORKBOOK_LIMIT_EXCEEDED",413,"Workbook sheet limit exceeded.");
 const sheets:SheetClassification[]=[];let cells=0,empty=0;for(const name of wb.SheetNames){const sheet=wb.Sheets[name];const range=sheet["!ref"]?XLSX.utils.decode_range(sheet["!ref"]):null;if(!range){empty++;continue}const rows=Math.min(range.e.r-range.s.r+1,MAX_ROWS),cols=Math.min(range.e.c-range.s.c+1,MAX_COLUMNS);cells+=rows*cols;if(cells>MAX_CELLS)throw new AgentError("WORKBOOK_LIMIT_EXCEEDED",413,"Workbook inspection cell limit exceeded.");const matrix=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,raw:true,blankrows:false,defval:null}).slice(0,MAX_ROWS).map(r=>r.slice(0,MAX_COLUMNS));const nonempty=matrix.flat().filter(v=>v!==null&&v!=="");if(!nonempty.length){empty++;continue}const headerRow=matrix.slice(0,12).sort((a,b)=>b.filter(v=>typeof v==="string").length-a.filter(v=>typeof v==="string").length)[0]??[];const formulas=Object.values(sheet).filter(v=>v&&typeof v==="object"&&"f" in v).length;const fp:SheetFingerprint={sheet_name:name,row_count:range.e.r-range.s.r+1,column_count:range.e.c-range.s.c+1,inspected_cells:rows*cols,numeric_density:Number((nonempty.filter(v=>typeof v==="number").length/nonempty.length).toFixed(2)),date_density:Number((nonempty.filter(v=>v instanceof Date).length/nonempty.length).toFixed(2)),formula_density:Number((formulas/Math.max(1,rows*cols)).toFixed(2)),normalized_headers:headerRow.filter(v=>typeof v==="string").map(normalizeFinancialLabel).filter(Boolean).slice(0,30),empty:false};sheets.push({sheet_name:name,fingerprint:fp,...classify(fp)})}
 const types=new Set(sheets.filter(s=>s.canonical_type!=="unsupported_or_unknown").map(s=>s.canonical_type));const compositionType=sheets.length===0||types.size===0?"unsupported_or_unknown_workbook":types.size>1?"mixed_financial_workbook":types.has("mapping_reference")?"reference_or_mapping_workbook":"single_purpose_workbook";const warnings:string[]=[];const hasMacros=document.extension===".xlsm"||document.buffer.includes(Buffer.from("vbaProject.bin"));const hasExternalLinks=document.buffer.includes(Buffer.from("externalLinks"));if(hasMacros)warnings.push("Macro-enabled container detected; VBA was not loaded or executed.");if(hasExternalLinks)warnings.push("External workbook links detected; no external target was fetched.");const composition:WorkbookComposition={type:compositionType,display_label:compositionType==="mixed_financial_workbook"?`Mixed Financial Workbook — ${sheets.length} sheets detected`:label(compositionType as never),sheet_count:wb.SheetNames.length,included_sheets:sheets.filter(s=>s.included_in_analysis).length,ignored_empty_sheets:empty,high_confidence_sheets:sheets.filter(s=>!s.review_required).length,review_required_sheets:sheets.filter(s=>s.review_required).length,detected_languages:[...new Set(sheets.map(s=>s.detected_language).filter(x=>x!=="unknown"))],warnings,recommended_primary_entry_point:sheets.find(s=>s.canonical_type==="income_statement")?.recommended_workflow??sheets.find(s=>s.included_in_analysis)?.recommended_workflow??"intake_review"};
 return {workbook_fingerprint:{file_name:document.fileName,format:document.extension.slice(1) as "xlsx"|"xlsm",sheet_count:wb.SheetNames.length,inspected_sheet_count:sheets.length,has_macros:hasMacros,has_external_links:hasExternalLinks,warnings},sheets,composition,review_tasks:sheets.filter(s=>s.review_required).map(s=>({sheet_name:s.sheet_name,reason:s.warnings[0]??"Classification confirmation required.",proposed_type:s.canonical_type,candidates:s.candidates,actions:["accept","change","include","exclude","mark_as_reference"],persistence:"session_only"}))};
}
